// src/lib/components/page/Acknowledgements.svelte
<script lang="ts">

    import Parser from "$lib/models/chapter/Parser"
    import ChapterBody from "$lib/components/chapter/ChapterBody.svelte";
    import BookishEditor from "$lib/components/editor/BookishEditor.svelte";
    import Instructions from "$lib/components/page/Instructions.svelte";
    import { getEdition, isEditable } from "./Contexts";

    let edition = getEdition();
    let editable = isEditable();

	$: acksNode = Parser.parseChapter($edition, $edition.getAcknowledgements());

</script>

<Instructions>
    This section is not shown if empty.
    But surely you have someone to thank!
</Instructions>

<h2 class="bookish-header" id="acknowledgements">Acknowledgements</h2>

 <!-- If editable, show acknowledgements even if they're empty, otherwise hide -->
{#if editable }
    <BookishEditor
        ast={acksNode} 
        chapter={false}
        component={ChapterBody}
        placeholder="Who would you like to thank?"
        save={node => $edition.setAcknowledgements(node.toBookdown())}
    />
{:else if acksNode }
    <h2 class="bookish-header" id="acknowledgements">Acknowledgements</h2>
    <ChapterBody node={acksNode}/>
{/if}

// src/views/page/Acknowledgements.tsx
import React, { useContext } from "react"
import Edition from "../../models/book/Edition"
import { ChapterNode } from "../../models/chapter/ChapterNode"
import Parser from "../../models/chapter/Parser"
import ChapterBody from "../chapter/ChapterBody"
import BookishEditor from "../editor/BookishEditor"
import { EditorContext } from "./EditorContext"
import Instructions from "./Instructions"

const Acknowledgements = (props: { book: Edition }) => {

	const { editable } = useContext(EditorContext)

	const acknowledgementsHeader = <h2 className="bookish-header" id="acknowledgements">Acknowledgements</h2>
	const book = props.book
	const acksNode = Parser.parseChapter(book, book.getAcknowledgements());

	return <>
		<Instructions>
			This section is not shown if empty.
			But surely you have someone to thank!
		</Instructions>

		{/* If editable, show acknowledgements even if they're empty, otherwise hide */}
		{
			editable ? 
				<>
					{ acknowledgementsHeader }
					<BookishEditor<ChapterNode> 
						ast={acksNode} 
						save={(node: ChapterNode) => book.setAcknowledgements(node.toBookdown())}
						chapter={false}
						render={node => <ChapterBody node={node} placeholder="Who would you like to thank?"/>}
					/>
				</>
				:
				book.getAcknowledgements() ?
					<>
						{ acknowledgementsHeader }
						<ChapterBody node={acksNode}/>
					</>
					: null
		}
	</>
}

export default Acknowledgements
