// src/lib/components/page/Description.svelte
<script lang="ts">
    import Parser from "$lib/models/chapter/Parser";
    import ChapterBody from "$lib/components/chapter/ChapterBody.svelte";
    import BookishEditor from "$lib/components/editor/BookishEditor.svelte";
    import { getContext } from "svelte";
    import { EDITABLE, getEdition } from "./Contexts";

    let editable = getContext<boolean>(EDITABLE);
    let edition = getEdition();

	$: descriptionNode = Parser.parseChapter($edition, $edition.getDescription());

</script>

<div class="bookish-description">
    {#if editable}
        <BookishEditor 
            ast={descriptionNode} 
            save={node => $edition.setDescription(node.toBookdown())}
            chapter={false}
            component={ChapterBody}
            placeholder="What this book about?"
        />
    {:else}
        <ChapterBody node={descriptionNode}/>
    {/if}
</div>

// src/views/page/Description.tsx
import { useContext } from "react"
import Edition from "../../models/book/Edition"
import Parser from "../../models/chapter/Parser"
import ChapterBody from "../chapter/ChapterBody"
import BookishEditor from "../editor/BookishEditor"
import { EditorContext } from "./EditorContext"

const Description = (props: { book: Edition }) => {

	const { editable } = useContext(EditorContext)
	const book = props.book
	const descriptionNode = Parser.parseChapter(book, book.getDescription());

	return <>
		<div className="bookish-description">
		{
			editable ? 
				<BookishEditor 
					ast={descriptionNode} 
					save={node => book.setDescription(node.toBookdown())}
					chapter={false}
					autofocus={false}
					render={ node => <ChapterBody node={node} placeholder="What this book about?"/> }
				/>
				:
				<ChapterBody node={descriptionNode}/>
		}
		</div>
	</>

}

export default Description
