// src/lib/components/page/Glossary.svelte
<script lang="ts">
    import Header from "./Header.svelte"
    import Outline from './Outline.svelte'
    import Page from './Page.svelte'
    import type Edition from '$lib/models/book/Edition.js'
    import ChapterIDs from '$lib/models/book/ChapterID'
    import { getContext } from "svelte";
    import DefinitionView from "./DefinitionView.svelte";
    import { EDITABLE, EDITION } from "./Symbols";
    import type { Writable } from "svelte/store";
    import Instructions from "./Instructions.svelte";

    let edition = getContext<Writable<Edition>>(EDITION);
	let editable = getContext<boolean>(EDITABLE);

	$: glossary = $edition.getGlossary();
	// Sort by canonical phrases
	$: keys = glossary === undefined || Object.keys(glossary).length === 0 ? null : Object.keys(glossary).sort((a, b) => glossary[a].phrase.localeCompare(glossary[b].phrase));
	
	function addEmptyDefinition() {

		// Generate an ID.
		const letters = "abcdefghijklmnopqrstuvwxyz".split("");
		let id = "";
		while(id.length < 4 || $edition.hasDefinition(id))
			id = id + letters[Math.round(Math.random() * 26)];
		$edition.addDefinition(id, "", "", []);

	}

</script>

<Page title={`${$edition.getTitle()} - Glossary`}>
    <Header 
        label="Glossary title"
        getImage={() => $edition.getImage(ChapterIDs.GlossaryID)}
        setImage={(embed) => $edition.setImage(ChapterIDs.GlossaryID, embed)}
        header="Glossary"
        tags={$edition.getTags()}
    >
        <Outline
            slot="outline"
            previous={$edition.getPreviousChapterID(ChapterIDs.GlossaryID)}
            next={$edition.getNextChapterID(ChapterIDs.GlossaryID)}
        />
    </Header>
    {#if editable }
        <Instructions>
            Add definitions and then link to them in a chapter's text.
        </Instructions>
        <p><button on:click={addEmptyDefinition}>+</button></p>
    {/if}
    {#if keys === null }
        <p>This book has no glossary.</p>
    {:else}
        <div>
            <br/>
            <div class="bookish-table">
                <table>
                    <colgroup>
                        <col style="width: 40%" />
                        <col style="width: 60%" />
                    </colgroup>
                    <tbody>
                        {#each keys as id }<DefinitionView id={id} definition={glossary[id]} />{/each}
                    </tbody>
                </table>
            </div>
        </div>
    {/if}
</Page>

// src/views/page/Glossary.tsx
import React, { useContext, useEffect } from 'react'

import Header from "./Header"
import Outline from './Outline'
import Page from './Page'
import { renderNode } from '../chapter/Renderer'

import Book from '../../models/Book.js'
import Parser from '../../models/Parser'
import { EditorContext } from './Book'
import { Definition } from '../../models/Book.js'
import ConfirmButton from '../editor/ConfirmButton'

const Definition = (props: { id: string, definition: Definition }) => {

	const { id, definition } = props;
	const { editable, book } = useContext(EditorContext);

	return <tr>
		<td>
			<strong>{definition.phrase || <em>Phrase</em>}</strong>
			{ editable ? <><br/><span className="bookish-editor-note">{id}</span></> : null }
			{
				editable && book ?
				<>
					<br/>
					<ConfirmButton
						commandLabel="x"
						confirmLabel="Confirm"
						command={() => book.removeDefinition(id)}
					/>
				</> : null
				
			}
		</td>
		<td>
			{ 
				definition.definition === "" ? 
					<em>Definition</em> :
					renderNode(Parser.parseFormat(undefined, definition.definition)) 
			}
			<br/><br/>
			{
				definition.synonyms === undefined || definition.synonyms.length === 0 ?
					(editable ? <em>Synonyms</em> : null) :
					<span><em>{definition.synonyms.join(", ")}</em></span> 
			}
		</td>
	</tr>

}

const Glossary = (props: { book: Book }) => {

	const { editable } = useContext(EditorContext);

	useEffect(() => {
	    // Always start at the top of the page.
		window.scrollTo(0, 0)
	}, [])

	let book = props.book;
	let glossary = book.getGlossary();
	// Sort by canonical phrases
	let keys = glossary === undefined || Object.keys(glossary).length === 0 ? null : Object.keys(glossary).sort((a, b) => glossary[a].phrase.localeCompare(glossary[b].phrase));

	function addEmptyDefinition() {

		// Generate an ID.
		const letters = "abcdefghijklmnopqrstuvwxyz".split("");
		let id = "";
		while(id.length < 4 || book.hasDefinition(id))
			id = id + letters[Math.round(Math.random() * 26)];
		book.addDefinition(id, "", "", []);

	}

	return (
		<Page>
			<Header 
				book={book}
				label="Glossary title"
				image={book.getImage(Book.GlossaryID)} 
				header="Glossary"
				tags={book.getTags()}
				outline={
					<Outline
						previous={book.getPreviousChapterID(Book.GlossaryID)}
						next={book.getNextChapterID(Book.GlossaryID)}
					/>
				}
			/>
			{
				editable ?
				<>
					<p>Add definitions and then link to them in a chapter's text.</p>
					<p><button onClick={addEmptyDefinition}>+</button></p>
				</> : null
			}
			{
				keys === null ? 
					<p>This book has no glossary.</p> :
					<div>
						<br/>
						<div className="bookish-table">
							<table>
								<colgroup>
									<col style={{width: "40%" }} />
									<col style={{width: "60%" }} />
								</colgroup>
								<tbody>
								{ keys.map((id, index) => <Definition key={index} id={id} definition={glossary[id]} />) }
								</tbody>
							</table>
						</div>
					</div>
			}
		</Page>
	);

}

export default Glossary
