// src/lib/components/page/ThemeEditor.svelte
<script lang="ts">
    import Header from "./Header.svelte";
    import Outline from './Outline.svelte';
    import Page from './Page.svelte';
    import { BookishTheme, CriticalTheme, HumanTheme, SeriousTheme, SketchyTheme, TechTheme } from '$lib/models/book/Theme'
    import ConfirmButton from '$lib/components/editor/ConfirmButton.svelte'
    import Instructions from './Instructions.svelte'
    import ThemeSetEditor from './ThemeSetEditor.svelte'
    import ThemeEditorPreview from './ThemeEditorPreview.svelte'
    import External from "../External.svelte";
    import { getEdition } from "./Contexts";
    import TextEditor from "../editor/TextEditor.svelte";
    import type Theme from "$lib/models/book/Theme";
    import Button from "../app/Button.svelte";

    const themes: Record<string,Theme> = {
        Bookish: BookishTheme,
        Serious: SeriousTheme,
        Tech: TechTheme,
        Human: HumanTheme,
        Sketchy: SketchyTheme,
        Critical: CriticalTheme,
    };

    let edition = getEdition();
    $: theme = $edition.getTheme();

    function getEmptyGroup(group: Record<string,string>) {
        const empty: Record<string, string> = {};
        for(const key in Object.keys(group))
            empty[key] = "";
        return empty;
    }

</script>

<Page title={`${$edition.getTitle()} - Theme`}>
    <Header 
        label="Theme"
        getImage={() => null}
        setImage={ () => undefined}
        header="Theme"
    >
        <Outline
            slot="outline"
            previous={null}
            next={null}
        />
    </Header>

    <Instructions>
        This is the theme editor. 
        You can use it to choose from existing themes or create a custom theme for your book's appearance.
        To use it, you'll need to know a bit about how to format CSS <External to="https://developer.mozilla.org/en-US/docs/Web/CSS/color">colors</External>, <External to="https://developer.mozilla.org/en-US/docs/Web/CSS/font-size">fonts</External>, and <External to="https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units">sizes</External>.
    </Instructions>

    {#each Object.entries(themes) as [ name, option ] }
        <Button tooltip="Choose the {name} theme" command={() => $edition.setTheme(option)} disabled={theme === option}>{name}</Button>
    {/each}
    <!-- If it's not one of the  -->
    {#if theme === null || Object.values(themes).includes(theme)}
        <Button tooltip="Create a custom theme" command={() => $edition.setTheme({ ...(theme === null ? BookishTheme : theme ) })}>Customize</Button>
    {:else}
        <ConfirmButton
            tooltip="Change the theme to the default Bookish theme."
            commandLabel="Revert to default"
            confirmLabel="Delete your theme?"
            command={() => $edition.setTheme(null)}
        />
        <ThemeEditorPreview theme={theme}/>
        <ThemeSetEditor header={"Light mode colors"} group="light" properties={theme.light ?? getEmptyGroup(BookishTheme.light)} />
        <ThemeSetEditor header={"Dark mode colors"} group="dark" properties={theme.dark ?? getEmptyGroup(BookishTheme.dark)} />
        <ThemeSetEditor header={"Fonts"} group="fonts" properties={theme.fonts ?? getEmptyGroup(BookishTheme.fonts)} />
        <ThemeSetEditor header={"Font sizes"} group="sizes" properties={theme.sizes ?? getEmptyGroup(BookishTheme.sizes)} />
        <ThemeSetEditor header={"Font weights"} group="weights" properties={theme.weights ?? getEmptyGroup(BookishTheme.weights)} />
        <ThemeSetEditor header={"Spacing"} group="spacing" properties={theme.spacing ?? getEmptyGroup(BookishTheme.spacing)} />

        <div class="bookish-table">
            <table >
                <tbody>
                    <tr>
                        <td>
                            <em>Add URLs to your own CSS to customize fonts and styles further.</em>
                        </td>
                        <td style='text-align:right;'>
                            <Button tooltip="Add a CSS import" command={() => {
                                if(theme === null) return;
                                if(theme.imports === undefined)
                                    theme.imports = [];
                                theme.imports.push("");
                                $edition.setTheme(theme);
                            }}>+</Button>
                        </td>
                    </tr>
                    {#each theme.imports ?? [] as url, index}
                        <tr>
                            <td>
                                <TextEditor 
                                    startText={url} 
                                    label={`CSS url`}
                                    placeholder={"CSS url"}
                                    valid={ () => undefined }
                                    save={text => {
                                        const newTheme = { ... theme };
                                        if(newTheme.imports === undefined) newTheme.imports = [];
                                        newTheme.imports[index] = text;
                                        $edition.setTheme(theme);
                                    }}
                                />
                            </td>
                            <td style="text-align: right">
                                <Button tooltip="Remove this CSS import" command={() => {
                                    theme?.imports?.splice(index, 1);
                                    $edition.setTheme(theme);
                                }}>–</Button>
                            </td>
                        </tr>
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}

</Page>

// src/views/page/ThemeEditor.tsx
import { useContext } from 'react';
import Header from "./Header";
import Outline from './Outline';
import Page from './Page';
import Edition from '../../models/book/Edition'
import { Theme, defaultTheme } from '../../models/book/Theme'
import Parser from '../../models/chapter/Parser';
import TextEditor from '../editor/TextEditor';
import ConfirmButton from '../editor/ConfirmButton';
import Instructions from './Instructions';
import { EditorContext } from './EditorContext';
import { DarkModeContext } from './DarkModeContext';
import ChapterBody from '../chapter/ChapterBody';

const Preview = (props: { theme: Theme }) => {

	const { darkMode } = useContext(DarkModeContext);

	const preview = Parser.parseChapter(undefined, `
		# Header 1
		## Header 2
		### Header 3
		
		This is how a sentence with _various_ *formatting* ^will^ look.

		* How does it look?
		* Would you change anything?	
	`);

	return <div className="bookish-theme-preview" style={{ backgroundColor: darkMode? props.theme.dark.backgroundColor : props.theme.light.backgroundColor }}>
		<ChapterBody node={preview}/>
	</div>
}

const placeholders = {
	light: "CSS color",
	dark: "CSS color",
	fonts: "CSS font name",
	sizes: "CSS font size",
	weights: "CSS font weights",
	spacing: "CSS length"
};

const VariableEditor = ( props: { group: string, name: string, value: string }) => {

	const { group, name, value } = props;
	const { edition: book } = useContext(EditorContext);
	if(book === undefined) return <span>{ value }</span>;

	return <tr>
		<td>{name.replace(/([a-z])([A-Z])/g, "$1 $2").split(" ").map(s => s.charAt(0).toUpperCase() + s.substring(1)).join(" ")}</td>
		<td style={{ textAlign: "right"}}>
			<TextEditor 
				text={value} 
				label={`${name} editor`}
				placeholder={group in placeholders ? (placeholders as Record<string,string>)[group] : "value"}
				valid={ text => undefined }
				save={text => book.setThemeValue(group, name, text)}
			/>
		</td>
	</tr>

};

const ThemeSetEditor = ( props: { header: string, group: string, theme: Record<string, Record<string,string>>}) => {

	const { header, group, theme } = props;
	const set = theme[group];

	return <>
		<h2>{header}</h2>
		<div className="bookish-table">
			<table>
				<tbody>
				{
					Object.keys(set).sort().map((name, index) => <VariableEditor key={index} group={group} name={name} value={set[name]} />)
				}
				</tbody>
			</table>
		</div>
	</>
};

const ThemeEditor = (props: { book: Edition }) => {

	const { book } = props;

	const theme = book.getTheme();

	return (
		<Page>
			<Header 
				book={props.book}
				label="Theme"
				getImage={() => null}
				setImage={embed => undefined}
				header="Theme"
				outline={
					<Outline
						previous={null}
						next={null}
					/>
				}
			/>

			<Instructions>
				This is the theme editor. 
				You can use it to choose from existing themes or create a custom theme for your book's appearance.
				To use it, you'll need to know a bit about how to format CSS <a target="_blank" href="https://developer.mozilla.org/en-US/docs/Web/CSS/color">colors</a>, <a target="_blank" href="https://developer.mozilla.org/en-US/docs/Web/CSS/font-size">fonts</a>, and <a target="_blank" href="https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units">sizes</a>.
			</Instructions>

			{
				theme === null ?
					<button onClick={() => book.setTheme(defaultTheme)}>Customize</button> :
					<ConfirmButton
						commandLabel="Revert to default"
						confirmLabel="Delete your theme?"
						command={() => book.setTheme(null)}
					/>
			}
			{
				theme !== null ?
					<>
						<Preview theme={theme}/>
						<ThemeSetEditor header={"Light mode colors"} group="light" theme={theme} />
						<ThemeSetEditor header={"Dark mode colors"} group="dark" theme={theme} />
						<ThemeSetEditor header={"Fonts"} group="fonts" theme={theme} />
						<ThemeSetEditor header={"Font sizes"} group="sizes" theme={theme} />
						<ThemeSetEditor header={"Font weights"} group="weights" theme={theme} />
						<ThemeSetEditor header={"Spacing"} group="spacing" theme={theme} />
					</> : null
			}

		</Page>
	)

}

export default ThemeEditor;
