// src/routes/finishlogin/+page.svelte
<script lang="ts">
    import { isSignInWithEmailLink, signInWithEmailLink } from "firebase/auth"
    import { onMount } from "svelte";
    import { auth } from "../../lib/models/Firebase";
    import Link from "../../lib/components/Link.svelte";
    import { goto } from "$app/navigation";
	
	let error: string | undefined = undefined;

	const messages: Record<string, string> = {
		"auth/id-token-expired": "This link expired.",
		"auth/id-token-revoked": "This link isn't valid anymore.",
		"auth/insufficient-permission": "This email doesn't have permission to create an account.",
		"auth/internal-error": "There's a problem at Google.",
		"auth/invalid-argument": "This link isn't valid.",
		"auth/invalid-email": "This wasn't a valid email.",
	};

    onMount(() => {

		if (auth && isSignInWithEmailLink(auth, window.location.href)) {
			// If this is on the same device and browser, then the email should be in local storage.
			let email = window.localStorage.getItem('email');
	
			// If not, ask the user to confirm it.
			if (!email)
				email = window.prompt("It appears you opened your login link on a different device or browser. Can you confirm your email?");
	
			// If there's an email, try signing in.
			if(email)
				signInWithEmailLink(auth, email, window.location.href)
					.then(() => {
						
						// Clear email from storage now that the user is logged in.
						window.localStorage.removeItem('email');
						
						// Navigate to the home page.
						goto("/write");
	
					})
					.catch((err: { code: string }) => {
						error = messages[err.code] ?? "There was a problem logging you in.";
					});
			// Otherwise, give some feedback.
			else 
				error = "Can't log in without an email address. Refresh the page to try again.";
					
		}
		// GIve some feedback if the email link isn't valid.
		else 
			error = "This isn't a valid login link.";
	
	});

</script>

<h1>Logging in…</h1>
{#if error}
    <div class="bookish-app-alert">{error}</div>
    <Link to="/login">Try again?</Link>
{:else}
    <p>Redirecting...</p>
{/if}

// src/views/app/FinishLogin.jsx
import React from "react"
import { getAuth, isSignInWithEmailLink, signInWithEmailLink } from "firebase/auth"
import { useNavigate } from "react-router-dom"

export default function FinishLogin() {

	const navigate = useNavigate()
	const auth = getAuth();

	if (isSignInWithEmailLink(auth, window.location.href)) {
		// Additional state parameters can also be passed via URL.
		// This can be used to continue the user's intended action before triggering
		// the sign-in operation.
		// Get the email if available. This should be available if the user completes
		// the flow on the same device where they started it.
		let email = window.localStorage.getItem('email');
		if (!email) {
			// TODO Handle sign in on different device
			// User opened the link on a different device. To prevent session fixation
			// attacks, ask the user to provide the associated email again. For example:
			email = window.prompt('Please provide your email for confirmation');
		}
		// The Firebase client SDK will parse the code.
		signInWithEmailLink(auth, email, window.location.href)
			.then((result) => {
				
				// Clear email from storage.
				window.localStorage.removeItem('email');
				
				// You can access the new user via result.user
				// Additional user info profile not available via:
				// result.additionalUserInfo.profile == null
				// You can check if the user is new or existing:
				// result.additionalUserInfo.isNewUser

				// Navigate to the home page.
				navigate("/dashboard")

			})
			.catch((error) => {
				// TODO Handle error
				// Some error occurred, you can inspect the code: error.code
				// Common errors could be invalid email and invalid or expired OTPs.
			});
	}

	return <>
		<p>Finishing login...</p>
	</>

}
