// src/routes/Header.svelte
<script lang="ts">
    import Link from "$lib/components/app/Link.svelte";
    import { getAuth } from "$lib/components/page/Contexts";
    import { getSubdomain, pathWithoutSubdomain } from "../lib/util/getSubdomain";

    let subdomain = getSubdomain();

    let auth = getAuth();

    // Ask the auth context to logout, and provided an error if it fails.
    async function handleLogout() {
        $auth.logout()
    }

    function getLink(path: string) {
		return subdomain !== undefined ? pathWithoutSubdomain(path) : path;
	}

</script>

<div class="header">
    <Link to={getLink("/")}>Home</Link>
    <Link to={getLink("/read")}>Read</Link>
    <Link to={getLink("/write")}>Write</Link>
    {#if $auth.user && $auth.user.email }
        <Link to={getLink("/")} before={handleLogout}>Logout </Link>
        <Link to={getLink("/email")}>{$auth.user.email}</Link>
    {:else}
        <Link to={getLink("/login")}>Login</Link>
    {/if}
</div>

<style>
    .header {
        margin-top: var(--app-chrome-padding); 
        margin-bottom: var(--app-chrome-padding); 
    }

    .header > :global(a) {
        display: inline-block;
        margin-right: calc(2 * var(--app-chrome-padding));
    }
</style>

// src/views/app/Header.jsx
import React from "react"
import { useAuth } from "./AuthContext"
import { Link } from "react-router-dom"

export default function Header() {

	const { currentUser, logout } = useAuth()

	// Ask the auth context to logout, and provided an error if it fails.
	async function handleLogout() {
		try {
			await logout()
		} catch {
			// TODO Handle errors.
		}
	}
	
	return <div className="bookish-app-header">
		<img src="images/icons/icon.png"/>
		<Link to="/"> Home</Link>
		<Link to="/read">Read</Link>
		<Link to="/write">Write</Link>
		<Link to="/about">About</Link>
		{
			currentUser === null ?
				<Link to="/login">Login</Link> :
				<Link to="/" onClick={handleLogout}>Logout</Link>		
		}
		<small>{ currentUser && currentUser.email }</small>
	</div>
}
