// src/routes/login/+page.svelte
<script lang="ts">
    import { getContext } from "svelte";
    import type { Writable } from "svelte/store";
    import type Authentication from "../../lib/components/Authentication";

	let email: HTMLInputElement;
	let auth = getContext<Writable<Authentication>>("auth");

	// Not loading by default
	let loading = false;

	// Track feedback with state
	let feedback = "";

	async function handleSubmit() {

		// Enter loading state, try to login and wait for it to complete, and then leave loading state.
		try {
			// Give some feedback when loading.
			loading = true;
			await $auth.login(email.value);
			feedback = "Check your email for a login link.";
		} catch(err) {
			feedback = "Uh oh! Couldn't connect to the server.";
			console.error(err);
		} finally {
			loading = false;
		}

	}

</script>

<h1>Login to write</h1>

<p>We'll send you an email each time to login, no password required.</p>

<form on:submit|preventDefault={handleSubmit}>
    <input autocomplete="username" type="email" placeholder="email" bind:this={email} required disabled={loading} /> <button type="submit" disabled={loading}>Login</button>
</form>

{#if feedback }
    <div class="bookish-app-alert">{feedback}</div>
{/if}

// src/views/app/Login.jsx
import React, { useRef, useState } from "react"
import { useAuth } from "./AuthContext"

export default function Login() {

	const emailRef = useRef()
	const { login } = useAuth()

	// Track errors with state
	const [ error, setError ] = useState("")

	// Not loading by default
	const [ loading, setLoading ] = useState(false)

	// Track feedback with state
	const [ feedback, setFeedback ] = useState("")

	async function handleSubmit(e) {

		// Prevent page reload
		e.preventDefault();

		// Enter loading state, try to login and wait for it to complete, and then leave loading state.
		try {
			setLoading(true);
			await login(emailRef.current.value);
			setFeedback("Check your email for a link.")
		} catch(err) {
			setError("Failed to create an account: " + err)
		}
		setLoading(false);

	}

	return <>

		<h1>Ready to write?</h1>

		<p>We'll send you an email to login, no password required.</p>

		{/* Show errors if there are any */}
		{ error && <div className="bookish-app-alert">{error}</div> }

		{/* Show feedback if there is any */}
		{ feedback && <div className="bookish-app-alert">{feedback}</div> }

		<form onSubmit={handleSubmit}>
			<input type="email" placeholder="email" ref={emailRef} required />
			<button type="submit" disabled={loading}>Login</button>
		</form>
	</>

}
