// src/lib/components/chapter/Block.svelte
<script lang="ts">
    import type BlockNode from "$lib/models/chapter/BlockNode";
    import CalloutNode from "$lib/models/chapter/CalloutNode";
    import CodeNode from "$lib/models/chapter/CodeNode";
    import EmbedNode from "$lib/models/chapter/EmbedNode";
    import ErrorNode from "$lib/models/chapter/ErrorNode";
    import ListNode from "$lib/models/chapter/ListNode";
    import ParagraphNode from "$lib/models/chapter/ParagraphNode";
    import QuoteNode from "$lib/models/chapter/QuoteNode";
    import RuleNode from "$lib/models/chapter/RuleNode";
    import TableNode from "$lib/models/chapter/TableNode";

    import Callout from "./Callout.svelte";
    import CaptionedCode from "./CaptionedCode.svelte";
    import Embed from "./Embed.svelte";
    import ErrorMessage from "./ErrorMessage.svelte";
    import List from "./List.svelte";
    import Paragraph from "./Paragraph.svelte";
    import Quote from "./Quote.svelte";
    import Rule from "./Rule.svelte";
    import Table from "./Table.svelte";
    import Problem from "./Problem.svelte";

    export let node: BlockNode;

</script>

{#if node instanceof ParagraphNode}<Paragraph {node} />
{:else if node instanceof ListNode}<List {node} />
{:else if node instanceof EmbedNode}<Embed {node} />
{:else if node instanceof CalloutNode}<Callout {node} />
{:else if node instanceof QuoteNode}<Quote {node} />
{:else if node instanceof CodeNode}<CaptionedCode {node} />
{:else if node instanceof ErrorNode}<ErrorMessage {node} />
{:else if node instanceof RuleNode}<Rule {node} />
{:else if node instanceof TableNode}<Table {node} />
{:else}<p><Problem>Unknown node type</Problem></p>
{/if}

// src/views/chapter/Block.tsx
import { BlockNode } from "../../models/chapter/BlockNode";
import { CalloutNode } from "../../models/chapter/CalloutNode";
import { CodeNode } from "../../models/chapter/CodeNode";
import { EmbedNode } from "../../models/chapter/EmbedNode";
import { ErrorNode } from "../../models/chapter/ErrorNode";
import { ListNode } from "../../models/chapter/ListNode";
import { ParagraphNode } from "../../models/chapter/ParagraphNode";
import { QuoteNode } from "../../models/chapter/QuoteNode";
import { RuleNode } from "../../models/chapter/RuleNode";
import { TableNode } from "../../models/chapter/TableNode";
import Callout from "./Callout";
import CaptionedCode from "./CaptionedCode";
import Embed from "./Embed";
import ErrorMessage from "./ErrorMessage";
import List from "./List";
import Paragraph from "./Paragraph";
import Quote from "./Quote";
import Rule from "./Rule";
import Table from "./Table";

const Block = (props: { node: BlockNode }) => {

    const { node } = props;

    return node instanceof ParagraphNode ? <Paragraph node={node} /> :
        node instanceof ListNode ? <List node={node} /> :
        node instanceof EmbedNode ? <Embed node={node} /> :
        node instanceof CalloutNode ? <Callout node={node} /> :
        node instanceof QuoteNode ? <Quote node={node} /> :
        node instanceof CodeNode ? <CaptionedCode node={node} /> :
        node instanceof ErrorNode ? <ErrorMessage node={node} /> :
        node instanceof RuleNode ? <Rule node={node} /> :
        node instanceof TableNode ? <Table node={node} /> :
        <p>Unknown node type</p>

};

export default Block;
