// src/lib/components/chapter/Embed.svelte
<script lang="ts">
    import type EmbedNode from "$lib/models/chapter/EmbedNode";
    import renderPosition from './renderPosition';
    import { storage } from '$lib/models/Firebase';
    import Format from './Format.svelte';
    import { getCaret, getEdition, isEditable } from "../page/Contexts";

    export let node: EmbedNode;
    export let placeholder: string | undefined = undefined;

    $: url = node.getURL();
	$: position = node.getPosition();
	$: description = node.getDescription();
	$: credit = node.getCredit();
	$: caption = node.getCaption();

    let caret = getCaret();
    let editable = isEditable();
    let edition = getEdition();

	let dragging = false;
	let dragFeedback: undefined | string = undefined;
	let imageError = false;

	function handleDrop(event: DragEvent) {
		event.preventDefault();
		if(event.dataTransfer?.items) {
			// Get the files and convert them to file opens, then filter by allowed file extensions
			const imageFiles = [...event.dataTransfer.items]
				.filter(item => item.kind === 'file')
				.map(item => item.getAsFile())
				.filter(file => file !== null && /.*\.(jpg|jpeg|png)/i.test(file.name));
			if(imageFiles.length === 0)
				dragFeedback = "Only JPEG or PNG images are allowed.";
			else if(imageFiles.length > 1)
				dragFeedback = "Only one image at a time please!";
			else {
				dragFeedback = "Uploading…";

				const file = imageFiles[0];
				const media = $edition.getBook()?.getMedia();

				if(file === null) return;
				if(storage === undefined) return;
				if(media === undefined) return;
		
				media.upload(file, 
					(progress: number) => dragFeedback = `${progress}% done`,
					(error: string) => { dragFeedback = error; dragging = false; },
					(url: string, thumbnails: string) => {
						// Upload completed successfully, now we can get the download URL
						$caret?.edit(node, node.withURLs(url, thumbnails).withDescription(""));
						dragging = false;
						dragFeedback = undefined;
					}
				);				
			}

		}
	}

	function handleDrag(event: DragEvent) { 
		event?.preventDefault(); 
		dragging = true;
		dragFeedback = "Drop to upload…";
	}

	function handleDragLeave(event: DragEvent) { 
		if(event.target !== event.currentTarget) return;
		event?.preventDefault(); 
		dragging = false;
		dragFeedback = undefined;
	}

	function handleLoad() {
		imageError = false;
	}

	function handleError() {
		imageError = true;
	}

</script>

<div class={"bookish-figure " + renderPosition(position)} data-nodeid={node.nodeID}>
    {#if url.trim().length === 0 }
        {#if editable }
            <div 
                class={`bookish-figure-unspecified ${dragging ? "bookish-figure-dragging" : ""}`}
                on:drop|preventDefault={handleDrop}
                on:dragover={handleDrag}
                on:dragleave={handleDragLeave}
            >{
                dragFeedback !== undefined ? dragFeedback :
                placeholder !== undefined ? placeholder :
                    "Click or drag to choose or upload an image, or enter an image or video URL."
            }
            </div>
        {:else}
            <div class="bookish-figure-unspecified">No image or video specified</div>
        {/if}
    {:else}
        {#if url.includes("https://www.youtube.com") || 
            url.includes("https://youtu.be") || 
            url.includes("https://www.tiktok.com") || 
            url.includes("vimeo.com") }
            <div class="bookish-figure-embed">
                <iframe 
                    class="bookish-figure-frame"
                    title="Embedded video content from streaming service"
                    src={url} 
                    frameBorder="0" 
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
                    allowFullScreen>
                </iframe>
            </div>
        {:else}
            <img 
                class={"bookish-figure-image"}
                src={url.startsWith("http") ? url : "images/" + url}
                srcset={node.hasSmallURL() ? `${node.getSmallURL()} 320w, ${url} 1024w` : undefined }
                sizes={node.hasSmallURL() ? "(min-width: 1024px) 1024px, 320px" : undefined }
                alt={description}
                on:load={handleLoad}
                on:error={handleError}
            />
        {/if}
    {/if}
    <div class="bookish-figure-caption">
        <div class="bookish-figure-credit">
            <Format node={credit} placeholder="credit" />
        </div>
        <Format node={caption} placeholder="caption" />
    </div>
    {#if imageError }
        <div class="bookish-figure-unspecified">{ editable ? "Unable to load image. Is the URL correct? Are you offline?" : "Unable to load image" }</div>
    {/if}
</div>

// src/views/chapter/Embed.tsx
import React, { useContext, useState } from 'react';
import { EmbedNode } from "../../models/chapter/EmbedNode";
import renderPosition from './renderPosition';
import { storage } from '../../models/Firebase';
import Format from './Format';
import { CaretContext, CaretContextType } from '../editor/CaretContext';
import { EditorContext } from '../page/EditorContext';

const Embed = (props: { node: EmbedNode }) => {

	const { node } = props
	const url = node.getURL();
	const position = node.getPosition();
	const description = node.getDescription();
	const credit = node.getCredit();
	const caption = node.getCaption();

	const { editable, edition } = useContext(EditorContext);
    const caret = useContext<CaretContextType>(CaretContext);

	const [ dragging, setDragging ] = useState(false);
	const [ dragFeedback, setDragFeedback ] = useState<undefined|string>(undefined);
	const [ imageError, setImageError ] = useState<boolean>(false);

	function handleDrop(event: React.DragEvent<HTMLDivElement>) {
		event.preventDefault();
		if(event.dataTransfer?.items) {
			// Get the files and convert them to file opens, then filter by allowed file extensions
			const imageFiles = [...event.dataTransfer.items]
				.filter(item => item.kind === 'file')
				.map(item => item.getAsFile())
				.filter(file => file !== null && /.*\.(jpg|jpeg|png)/i.test(file.name));
			if(imageFiles.length === 0)
				setDragFeedback("Only JPEG or PNG images are allowed.");
			else if(imageFiles.length > 1)
				setDragFeedback("Only one image at a time please!");
			else {
				setDragFeedback("Uploading…");

				const file = imageFiles[0];
				const media = edition?.getBook()?.getMedia();

				if(file === null) return;
				if(storage === undefined) return;
				if(media === undefined) return;
		
				media.upload(file, 
					(progress: number) => setDragFeedback(`${progress}% done`),
					(error: string) => { setDragFeedback(error); setDragging(false); },
					(url: string, thumbnails: string) => {
						// Upload completed successfully, now we can get the download URL
						caret?.edit(node, node.withURLs(url, thumbnails).withDescription(""));
						setDragging(false);
						setDragFeedback(undefined);
					}
				);				
			}

		}
	}

	function handleDrag(event: React.DragEvent<HTMLDivElement>) { 
		event?.preventDefault(); 
		setDragging(true); 
		setDragFeedback("Drop to upload…");
	}

	function handleDragLeave(event: React.DragEvent<HTMLDivElement>) { 
		if(event.target !== event.currentTarget) return;
		event?.preventDefault(); 
		setDragging(false); 
		setDragFeedback(undefined);
	}

	function handleLoad() {
		setImageError(false);
	}
	function handleError() {
		setImageError(true);
	}

	return <div className={"bookish-figure " + renderPosition(position)} data-nodeid={props.node.nodeID}>
			{
				url.trim().length === 0 ? 
					editable ? 
						<div 
							className={`bookish-figure-unspecified ${dragging ? "bookish-figure-dragging" : ""}`}
							onDrop={handleDrop}
							onDragOver={handleDrag}
							onDragLeave={handleDragLeave}
						>{
							dragFeedback === undefined ? 
								"Click or drag to choose or upload an image, or enter an image or video URL." :
								dragFeedback
						}</div> : 
						<div className="bookish-figure-unspecified">No image or video specified</div>
					:
				url.includes("https://www.youtube.com") || 
				url.includes("https://youtu.be") || 
				url.includes("https://www.tiktok.com") || 
				url.includes("vimeo.com") ?
					<div className="bookish-figure-embed">
						<iframe 
							className="bookish-figure-frame" 
							src={url} 
							frameBorder="0" 
							allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
							allowFullScreen>
						</iframe>
					</div> 
				:
					<img 
						className={"bookish-figure-image"}
						src={url.startsWith("http") ? url : "images/" + url}
						// If the image is hosted, included a source set
						srcSet={node.hasSmallURL() ? `${node.getSmallURL()} 320w, ${url} 1024w` : undefined }
						sizes={node.hasSmallURL() ? "(min-width: 1024px) 1024px, 320px" : undefined }
						alt={description}
						onLoad={handleLoad}
						onError={handleError}
					/>
			}
			<div className="bookish-figure-caption"><div className="bookish-figure-credit">{<Format node={credit} placeholder="credit" />}</div>{<Format node={caption} placeholder="caption" />}</div>
			{ 
				imageError ?
					<div className="bookish-figure-unspecified">{ editable ? "Unable to load image. Is the URL correct? Are you offline?" : "Unable to load image" }</div> :
					null
			}
		</div>

}

export default Embed;
