// src/lib/components/chapter/Label.svelte
<script lang="ts">
    import type LabelNode from "$lib/models/chapter/LabelNode"
    import Atom from '$lib/components/chapter/Atom.svelte';
    import { CHAPTER, EDITABLE } from "../page/Symbols";
    import { getContext } from "svelte";
    import type ChapterContext from "$lib/components/page/ChapterContext";

    export let node: LabelNode;

    let editable = getContext<boolean>(EDITABLE);
    let context = getContext<ChapterContext>(CHAPTER);

    $: ast = context.chapter.getAST();
    $: duplicate = ast === undefined ? false : ast.getLabels().filter(l => l.getMeta() === node.getMeta()).length > 1;

</script>

<Atom node={node}>
    <span 
        class={"bookish-label" + (context.highlightedID === node.getMeta() ? " bookish-content-highlight" : "")} 
        id={node.getMeta()}
        data-nodeid={node.nodeID}
    >
        {#if editable}
            <span class={`${duplicate ? "bookish-error" : ""}`}>•<code>{node.getMeta()}</code></span>
        {/if}
    </span>
</Atom>

// src/views/chapter/Label.tsx
import React, { useContext } from 'react'
import { ChapterContext } from './Chapter'
import { LabelNode } from "../../models/LabelNode"
import Atom from '../editor/Atom';
import { EditorContext } from '../page/Book';

const Label = (props: { node: LabelNode }) => {

    const { node } = props;
    const context = useContext(ChapterContext);
    const { editable } = useContext(EditorContext)

    const ast = context.chapter?.getAST();
    const duplicate = 
        ast === undefined ? 
        false : 
        ast.getLabels().filter(l => l.getMeta() === node.getMeta()).length > 1;


    const label = <span 
        className={"bookish-label" + (context.highlightedID === node.getMeta() ? " bookish-content-highlight" : "")} 
        id={node.getMeta()}
        data-nodeid={props.node.nodeID}
    >
        {editable ? <span className={`${duplicate ? "bookish-error" : ""}`}>•<code>{node.getMeta()}</code></span> : ""}
    </span>

    return <Atom
        node={node}
        textView={label}
    />;
}

export default Label;
