// src/lib/components/chapter/Paragraph.svelte
<script lang="ts">
    import type ParagraphNode from "$lib/models/chapter/ParagraphNode"
    import Format from './Format.svelte'
    import { getChapter } from "../page/Contexts";

    export let node: ParagraphNode;
    export let placeholder: string | undefined = undefined;

    let level = node.getLevel();
    let chapter = getChapter();

    const id = node.getLevel() === 0 ? undefined : "header-" + ($chapter.chapter.getAST()?.getHeaders().indexOf(node) ?? "");
    const classes = node.getLevel() === 0 ? undefined: "bookish-header" + ($chapter.highlightedID === id ? " bookish-content-highlight" : "")

</script>

{#if level === 0}
    <p data-nodeid={node.nodeID}><Format node={node.getFormat()} placeholder={placeholder ?? "¶"}/></p>
{:else}
    <svelte:element this={`h${level + 1}`} class={classes} id={id} data-nodeid={node.nodeID}><Format node={node.getFormat()} /></svelte:element>
{/if}

// src/views/chapter/Paragraph.tsx
import { useContext } from 'react'
import { ParagraphNode } from "../../models/chapter/ParagraphNode"
import { EditorContext } from '../page/EditorContext'
import { ChapterContext } from './ChapterContext'
import Format from './Format'

const Paragraph = (props: { node: ParagraphNode, placeholder?: string }) => {

    const { node, placeholder } = props
    const content = node.getFormat();
    const level = node.getLevel();
    const context = useContext(ChapterContext)
    const chapter = context.chapter?.getAST();

    const id = node.getLevel() === 0 ? undefined : "header-" + (chapter ? chapter.getHeaders().indexOf(node) : "")
    const classes = node.getLevel() === 0 ? undefined: "bookish-header" + (context.highlightedID === id ? " bookish-content-highlight" : "")

    const format = <Format node={content}/>

    return  content === undefined ? <></> :
        level === 0 ? <p data-nodeid={props.node.nodeID}><Format node={props.node.getFormat()} placeholder={placeholder ?? "¶"}/></p> :
        level === 1 ? <h2 className={classes} id={id} data-nodeid={props.node.nodeID}>{format}</h2> :
        level === 2 ? <h3 className={classes} id={id} data-nodeid={props.node.nodeID}>{format}</h3> :
            <h4 className={classes} id={id} data-nodeid={props.node.nodeID}>{format}</h4>

}

export default Paragraph
