// src/views/chapter/Chapter.tsx
import React, { useContext } from 'react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';

import Parser from "../../models/chapter/Parser"
import { ChapterNode } from "../../models/chapter/ChapterNode";
import Header from '../page/Header'
import Authors from "./Authors"
import Outline from '../page/Outline'
import Page from '../page/Page'

import smoothlyScrollElementToEyeLevel from '../util/Scroll'
import Marker from "../../assets/svg/marker.svg"
import Edition from '../../models/book/Edition'
import ChapterModel from '../../models/book/Chapter'
import TextEditor from '../editor/TextEditor';
import BookishEditor from '../editor/BookishEditor';
import Toggle from '../editor/Toggle';
import Instructions from '../page/Instructions';
import ChapterBody from './ChapterBody';
import { EditorContext } from '../page/EditorContext';
import { ChapterContext } from './ChapterContext';
import renderReference from './renderReference';

const Chapter = (props: { chapter: ChapterModel, book: Edition, print?: boolean }) => {

	// Keep track of the scroll position to facilitate reading during reloads.
	const rememberPosition = () => localStorage.setItem('scrollposition', "" + window.scrollY)

	// When the window resizes, the responsive layout might cause the marginals to move to the footer.
	// when this happens, we want to immediately remove all of the explicit positioning.
	const handleResize = () => layoutMarginals();
	
	// The currently selected marginal; we only do one at a time.
	let [ marginal, setMarginal ] = useState<string | undefined>(undefined);

	// Keep track of which hash mark is scrolled to
	let [ highlightedID, setHighlightedID ] = useState<string | undefined>(undefined);

	const { editable } = useContext(EditorContext);
	const navigate = useNavigate();

	const [, updateState] = React.useState<{}>();
	const forceUpdate = React.useCallback(() => updateState({}), []);

	// When this component is mounted...
	// 1) Subscribe and unsubscribe to window listeners
	// 2) Do initial layout of marginals
	// 3) Start observing any elements corresponding to the ID in the URL's hash string
	// 4) Clean up our mess after unmounting.
	useEffect(() => {

		// On render or when scrolling, see if the URL hash has changed and update state accordingly.
		// We also track whether we've scrolled to it.
		const observeHash = () => {

			// Get the ID without the hash and the corresponding element
			const elementID = window.location.hash.substring(1)
			const element = elementID ? document.getElementById(elementID) : null

			// If it's not empty, observe it, and remember what we're observing for highlighting
			if(element) {
				setHighlightedID(elementID)
				// Start watching this a few seconds after we see it, giving the for in-page scrolling.
				setTimeout(() => observer.observe(element), 2500)
			}
			
		}

		// Do things to do when scrolling
		const handleScroll = () => {

			// See if the outline is obscured by an image
			hideOutlineIfObscured()

			// See if there are any new hashes to observe. This is because
			// we're using react-router-hash-link, which doesn't trigger hashchange events for some reason.
			observeHash()
			
		}

		// Lay things out when the window or scroll changes.
		window.addEventListener('scroll', handleScroll)
		window.addEventListener('resize', handleResize)

		// Remember the scroll position before a refresh.
		// We have to do all of these because browser support varies.
		window.addEventListener("beforeunload", rememberPosition)
		window.addEventListener("visibilitychange", rememberPosition)
		window.addEventListener("pagehide", rememberPosition)
		
		// Start listening for hash changes, since we want to remove them upon scrolling away from them.
		window.addEventListener("pushstate", observeHash)
		window.addEventListener("popstate", observeHash)
		window.addEventListener("hashchange", observeHash)

		// Make an intersection observer to monitor the location of elements selected by the URL hash ID.
		const observer = new IntersectionObserver((entries => {
			// Go through all of the monitored elements
			entries.forEach(entry => {
				// If the observed element is out of view and in the hash, remove the hash 
				if(entry.intersectionRatio === 0 && entry.target.id === window.location.hash.substring(1)) {
					history.pushState("", document.title, window.location.pathname + window.location.search)
					observer.unobserve(entry.target)					
					setHighlightedID(undefined)
				}
			})
		}))
		
		// Do an initial check the hash to see if there's an ID to scroll to
		observeHash();

		// Position the marginals, since there's new content.
		layoutMarginals();

		// Listen to changes on the book and chapter.
		book.addListener(handleBookChange);
		chapter.addListener(handleBookChange);

		// Periodically save the chapter's edits.
		const chapterSaverID = setInterval(() => {
			chapter.saveEdits()
		}, 500);

		// On cleanup, unsubscribe from everything above.
		return () => {

			window.removeEventListener('scroll', handleScroll)
			window.removeEventListener('resize', handleResize)
	
			// Stop listening to page visibility changes.
			window.removeEventListener("beforeunload", rememberPosition)
			window.removeEventListener("visibilitychange", rememberPosition)
			window.removeEventListener("pagehide", rememberPosition)
	
			// Delete the remembered position so that the next page scrolls to top.
			localStorage.removeItem("scrollposition")

			// Stop listening for hash changes
			window.removeEventListener("pushstate", observeHash)
			window.removeEventListener("popstate", observeHash)
			window.removeEventListener("hashchange", observeHash)

			// Stop observing everything on unmount
			observer.disconnect()

			book.removeListener(handleBookChange)
			chapter.removeListener(handleBookChange)

			// Stop saving.
			clearInterval(chapterSaverID);
		}

	}, [])
	
	// Position the marginals on each render.
	useEffect(() => {
		layoutMarginals();
	});

	// Get the word and number to highlight from the URL
	const { word, number } = useParams();

	// This gets called after the page is done loading. There are various things we scroll to.
	const scrollToLastLocation = () => {

		// In case loading changed marginal positions
		layoutMarginals();

		// If there's a word we're trying to highlight in the URL path, scroll to the corresponding match.
		if(word && number) {
			const highlights = document.getElementsByClassName("bookish-text bookish-content-highlight")
			const num = parseInt(number)
			if(highlights.length > 0 && num < highlights.length && num >= 0) {
				smoothlyScrollElementToEyeLevel(highlights[num])
			}
		}
		// Otherwise, if there's an ID in the URL, jump to it.
		else if(highlightedID) {
			const el = document.getElementById(highlightedID as string)
			// If we found the element, remove the hash any time after a few seconds. See handleScroll for the removal logic.
			if(el) {
				smoothlyScrollElementToEyeLevel(el)
			}
		}
		else {			
			// If we got to this page through a refresh, scroll to 
			const entries = performance.getEntriesByType("navigation");
			const position = localStorage.getItem('scrollposition');
			if(position !== null && entries.length > 0 && (entries[entries.length - 1] as PerformanceNavigationTiming).type === "reload") {
				// Scroll to the previous position, if there was one, so that refresh preserves position.
				window.scrollTo(0, parseInt(position));
			} 
			// Otherwise, just scroll to the top.
			else {
				window.scrollTo(0, 0);
			}
		}

	}

	function handleBookChange() {
		forceUpdate();
	}

	// Prepare to render the chapter by getting some data from the chapter and book.
	const book = props.book;
	const chapter = props.chapter;
	const chapterID = chapter.getChapterID();
	const chapterNumber = book.getChapterNumber(chapterID);
	const chapterSection = book.getChapterSection(chapterID);
	const chapterAST = chapter.getAST();
	const citations = chapterAST ? chapterAST.getCitations() : undefined;
	const hasReferences = citations && citations.size > 0;

	return (
		<Page afterLoaded={scrollToLastLocation}>
			<div className="bookish-chapter">
				<Header 
					book={book}
					label="Chapter title"
					getImage={() => chapter.getImage()}
					setImage={embed => chapter.setImage(embed)}
					print={props.print}
					outline=
					{
						props.print ? 
						null :
						<Outline
							previous={book.getPreviousChapterID(chapterID)}
							next={book.getNextChapterID(chapterID)}
							listener={ (expanded: boolean, callback: Function) =>{
	
								// If the outline is being expanded, hide the marginal, otherwise leave it alone.
								if(expanded)
									setMarginal(undefined)
	
								// Check if we need to hide the outline after positioning.
								hideOutlineIfObscured();
	
							}}
							// Collapse the outline if a marginal is selected.
							collapse={marginal !== undefined}
						/>
					}
					before={
						<span>
						{/* Add an editable chapter ID if in editor mode */}
						{
							editable ?
								<span className="bookish-muted">
									<TextEditor 
										text={props.chapter.getChapterID()} 
										label="Chapter URL ID editor"
										save={ 
											// After the ID is edited, reload the page with the new URL.
											id => props.chapter.setChapterID(id)?.then(() => {
												const ref = props.book.getRef();
												if(ref?.id)
													navigate(`/write/${ref?.id}/${id}`)
											})
										}
										placeholder="chapter ID"
										valid={(newChapterID) => 
											!/^[a-zA-Z0-9]+$/.test(newChapterID) ? "Chapter IDs must be one or more letters or numbers" :
											props.chapter.getChapterID() !== newChapterID && props.book.hasChapter(newChapterID) ? "There's already a chapter that has this ID." :
											undefined
										}
										saveOnExit={true}
									/>
									<br/>
								</span>
								:
								null
						}
						{
							editable ?
								<Toggle on={props.chapter.isNumbered()} save={ on => chapter.setNumbered(on) }>
									{ chapterNumber !== undefined ? <span className="bookish-chapter-number">Chapter {chapterNumber}</span> : <span className="bookish-muted">Unnumbered</span> }
								</Toggle>
							:
							chapterNumber === undefined ? 
								null : 
								<span className="bookish-chapter-number">Chapter {chapterNumber}</span> 
						}
						{ 
							chapterSection === undefined ? 
								null : 
								<span className="bookish-section-name">&nbsp;&nbsp;{chapterSection}</span>
						}
						</span>						
					}
					header={chapter.getTitle()}
					tags={book.getTags()}
					/* If there are chapter authors, map them to authors declared in the book title, otherwise use all the authors of the book */
					after={
						<Authors 
							authors={ chapter.getAuthors() }
							inheritedAuthors={ book.getAuthors() }
							add={ () => chapter.addAuthor("") }
							edit={(index, text) => text.length === 0 ? chapter.removeAuthor(index) : chapter.setAuthor(index, text) }
						/>
					}
					save={ text => props.chapter.setTitle(text) }
				/>
				{/* We load this on the page but hide it; it's used as a filter for highlighing in CSS */}
				<img src={Marker} style={{display: "none"}}/>
				<Instructions>
					Edit your chapter's title, authors, and cover image above.
					You can also change the ID of the chapter, which appears in it's URL.
					Write your chapter text below, using the many formatting options in the toolbar above to format text, add headers, lists, tables, comments, citations, footnotes, and more.
					It's okay to try things, you can always undo!
					Saves are automatic, each time you stop typing.
				</Instructions>

				{ /* Render the chapter body, passing some context */ }
				<ChapterContext.Provider 
					value={{
							book: book, 
							chapter: chapter, 
							highlightedWord: word,
							highlightedID: highlightedID,
							marginalID: marginal,
							setMarginal: setMarginal,
							layoutMarginals: layoutMarginals
					}}
				>
				{
					chapterAST ?
						(
							editable ? 
								<BookishEditor<ChapterNode>
									ast={chapterAST}
									save={ (node: ChapterNode) => chapter.setAST(node) }
									chapter={true}
									autofocus
									render={node => <ChapterBody node={node} placeholder="Type here"/>}
								/> 
								: 
								<ChapterBody node={chapterAST} />
						) :
						<span>Loading...</span>
				}
				</ChapterContext.Provider>
				{
					!hasReferences ? null :
					<div>
						<h1 id="references" className="bookish-header">References</h1>

						<ol>
						{
							[...citations].sort().map(citationID => {
								let refs = book.getReferences();
								if(citationID in refs) {
									let ref = refs[citationID];
									return <li key={"citation-" + citationID} className={"bookish-reference"} id={"ref-" + citationID}>
										{ renderReference(Parser.parseReference(citationID, ref, book)) }
									</li>

								}
								else {
									return <li className="bookish-error" key={"citation-" + citationID}>Unknown reference: <code>{citationID}</code></li>;
								}
							})
						}
						</ol>
					</div>
				}
			</div>
		</Page>
	)

}

// Hides the outline if there's a left inset marginal that might overlap it.
// This operates on the DOM directly, as scroll position isn't easily managed in React.
function hideOutlineIfObscured() {

	// Get the outline's bounds.
	let outline = document.getElementsByClassName("bookish-outline")[0] as HTMLElement;

	// If there's no outline, don't bother.
	if(!outline)
		return

	// Set a threshold for hiding
	let threshold = 100;

	// If the outline isn't affixed to the footer
	if(window.getComputedStyle(outline).getPropertyValue("left") !== "0px") {

		let outlineRect = outline.getBoundingClientRect();
		let overlapRect: DOMRect | undefined = undefined;

		// Find the bottom-most left inset marginal within threshold of the outline.
		Array.from(document.getElementsByClassName("bookish-marginal-left-inset")).forEach(el => {
			let insetRect: DOMRect = el.getBoundingClientRect();
			if(!(outlineRect.bottom < insetRect.top - threshold || 
				outlineRect.top > insetRect.bottom + threshold))
				overlapRect = insetRect;
		});

		// If it overlaps, reduce opacity by the proportion of the vertical distance between two rectangles and the height of the marginal.
		if(overlapRect) {
			let overlap: DOMRect = overlapRect
			let distance = 
				outlineRect.bottom < overlap.top ? threshold :
				outlineRect.bottom < overlap.top + threshold ? threshold - (outlineRect.bottom - overlap.top) :
				outlineRect.top > overlap.bottom - threshold ? threshold - (overlap.bottom - outlineRect.top) :
				outlineRect.top > overlap.bottom ? threshold :
				0;
			let proportion = distance / threshold;
			outline.style.opacity = "" + (proportion * proportion);
		}
		// Otherwise, remove the dimming.
		else
			outline.style.removeProperty("opacity");
	}
	// If it is, it's always visible.
	else
		outline.style.removeProperty("opacity");

}

// After each render of the chapter, we need to adjust the layout of marginals, which by default are floating from
// their little spans within the body of the text. 
//
// We have to do two things:
//
// 1) Lay them out vertically so that they don't overlap.
// 2) Lay them out horizontally, so they're all left aligned with each other on the right margin of the text.
//
// We only want to do this if the marginals are floating; we exclude any marginals that are
// fixed in a fixed position.
function layoutMarginals() {

	// Get the chapter DOM node, so we can calculate margins.
	let chapter = document.getElementsByClassName("bookish-chapter-body")[0] as HTMLElement;

	// If there's no chapter rendered yet, stop.
	if(chapter === undefined)
		return;

	let book = document.getElementsByClassName("bookish")[0] as HTMLElement;

	// This is the grid line we'll aline all marginals too horizontally.
	let margin = chapter.getBoundingClientRect().width;

	// This will track the current leading bottom edge for laying out marginals.
	let currentBottom: number | null = null;

	// Are there any marginal right inset images that might overlap?
	let rightInsets = document.getElementsByClassName("bookish-marginal-right-inset");

	const marginals = document.getElementsByClassName("bookish-marginal")

	// Layout all of the marginals vertically to prevent overlaps.
	Array.from(marginals).forEach((element: Element) => {

		const el = element as HTMLElement;

		if(el === null)
			return;

		if(window.getComputedStyle(el).getPropertyValue("position") !== "fixed") {

			if(el.parentElement) {

				let containingMarginal = el.parentElement.closest(".bookish-marginal");

				// Get the bounds of this marginal so we know it's size.
				let elementBounds = el.getBoundingClientRect();

				// Get the bounds of this marginal's parent so we know it's vertical position.
				let parentBounds = el.parentElement.getBoundingClientRect();
				let parentTop = parentBounds.top + window.scrollY - (book.getBoundingClientRect().top + window.scrollY);

				// If it's inside a marginal, position it below the marginal.
				if(containingMarginal !== null && currentBottom) {
					el.style.left = "0";
					el.style.top = "" + (currentBottom - (containingMarginal.getBoundingClientRect().top + window.scrollY)) + "px";
					currentBottom = currentBottom + elementBounds.height;
				}
				else {
					// If we don't have a bottom yet, or the current above is above the parent's top,
					// then set the current bottom to the bottom of the parent.
					if(currentBottom === null || currentBottom < parentTop) {
						el.style.top = parentTop + "px";
						currentBottom = parentTop + elementBounds.height;
					}
					// Otherwise, put the marginal below the last marginal's bottom.
					else {
						el.style.top = currentBottom + "px";
						currentBottom = currentBottom + elementBounds.height;
					}

					// If there are any right insets, do any intersect with this marginal?
					// If so, move the marginal below them.
					if(rightInsets.length > 0) {
						Array.from(rightInsets).forEach(inset => {
							// Compute the global positions of the marginal and the potential inset.
							let insetBounds = inset.getBoundingClientRect();
							let insetTop = insetBounds.top + window.scrollY;
							let insetBottom = insetTop + insetBounds.height;
							let elementTop = el.getBoundingClientRect().top + window.scrollY;
							let elementBottom = elementTop + elementBounds.height;

							// If they overlap...
							if(currentBottom !== null) {
								if((elementTop <= insetTop && elementBottom >= insetTop) ||
									(elementTop <= insetBottom && elementBottom >= insetBottom) ||
									(elementTop >= insetTop && elementBottom <= insetBottom)) {
									// Calculate the new position based on the preferred position, minus the element's height (which was added above), plus the overlap between the inset and the marginal.
									let newTop = currentBottom - elementBounds.height + (insetBottom - elementTop);
									// Reposition the marginal.
									el.style.top = newTop + "px";
									// Update the new bottom.
									currentBottom = newTop + elementBounds.height;

								}
							}
						});
					}

					// Reposition the marginal horizontally.
					el.style.left = "calc(2rem + " + margin + "px)";
				}

			}

		}
		// If it's fixed, remove any explicitly set inline values.
		else {
			el.style.removeProperty("top");
			el.style.removeProperty("left");
		}
	});
	
}

export default Chapter;

// src/lib/components/page/Chapter.svelte
<script lang="ts">
    import Parser from "$lib/models/chapter/Parser"
    import type ChapterModel from '$lib/models/book/Chapter'

    import Header from '$lib/components/page/Header.svelte'
    import Authors from "$lib/components/page/Authors.svelte"
    import Outline from '$lib/components/page/Outline.svelte'
    import Page from '$lib/components/page/Page.svelte'
    import TextEditor from '$lib/components/editor/TextEditor.svelte';
    import BookishEditor from '$lib/components/editor/BookishEditor.svelte';
    import Toggle from '$lib/components/editor/Toggle.svelte';
    import Instructions from '$lib/components/page/Instructions.svelte';
    import ChapterBody from '$lib/components/chapter/ChapterBody.svelte';
    import PossibleReference from "./PossibleReference.svelte";

    import { CHAPTER, EDITABLE, getEdition, type ChapterStore } from "./Contexts";
    import { writable } from "svelte/store";
    import { getContext, onMount, setContext } from "svelte";
    import { hideOutlineIfObscured, layoutMarginals } from "./margins";
    import scrollToEyeLevel from "../../util/scrollToEyeLevel";
    import type ChapterContext from "$lib/components/page/ChapterContext";
    import { goto } from "$app/navigation";
    import type Chapter from "$lib/models/book/Chapter";
    import ChapterNode from "$lib/models/chapter/ChapterNode";

    export let chapter: ChapterModel;
    export let print: boolean = false;

    let edition = getEdition();
    let editable = getContext<boolean>(EDITABLE);

	// Keep track of the scroll position to facilitate reading during reloads.
	function rememberPosition() { localStorage.setItem('scrollposition', "" + window.scrollY); }

	// When the window resizes, the responsive layout might cause the marginals to move to the footer.
	// when this happens, we want to immediately remove all of the explicit positioning.
	function handleResize() { layoutMarginals(); }
	
	// The currently selected marginal; we only do one at a time.
	let marginal: string | undefined = undefined;

	// Keep track of which hash mark is scrolled to
	let highlightedID: string | undefined = undefined;

	// When this component is mounted...
	// 1) Subscribe and unsubscribe to window listeners
	// 2) Do initial layout of marginals
	// 3) Start observing any elements corresponding to the ID in the URL's hash string
	// 4) Clean up our mess after unmounting.
	onMount(() => {

		// On render or when scrolling, see if the URL hash has changed and update state accordingly.
		// We also track whether we've scrolled to it.
		const observeHash = () => {
			// Get the ID without the hash and the corresponding element
			const elementID = window.location.hash.substring(1)
			const element = elementID ? document.getElementById(elementID) : null

			// If it's not empty, observe it, and remember what we're observing for highlighting
			if(element) {
				highlightedID = elementID;
				// Start watching this a few seconds after we see it, giving the for in-page scrolling.
				setTimeout(() => observer.observe(element), 2500)
			}
		}

		// Do things to do when scrolling
		const handleScroll = () => {

			// See if the outline is obscured by an image
			hideOutlineIfObscured()

			// See if there are any new hashes to observe. This is because
			// we're using react-router-hash-link, which doesn't trigger hashchange events for some reason.
			observeHash()
			
		}

		// Lay things out when the window or scroll changes.
		window.addEventListener('scroll', handleScroll)
		window.addEventListener('resize', handleResize)

		// Remember the scroll position before a refresh.
		// We have to do all of these because browser support varies.
		window.addEventListener("beforeunload", rememberPosition)
		window.addEventListener("visibilitychange", rememberPosition)
		window.addEventListener("pagehide", rememberPosition)
		
		// Start listening for hash changes, since we want to remove them upon scrolling away from them.
		window.addEventListener("pushstate", observeHash)
		window.addEventListener("popstate", observeHash)
		window.addEventListener("hashchange", observeHash)

		// Make an intersection observer to monitor the location of elements selected by the URL hash ID.
		const observer = new IntersectionObserver((entries => {
			// Go through all of the monitored elements
			entries.forEach(entry => {
				// If the observed element is out of view and in the hash, remove the hash 
				if(entry.intersectionRatio === 0 && entry.target.id === window.location.hash.substring(1)) {
					history.pushState("", document.title, window.location.pathname + window.location.search)
					observer.unobserve(entry.target)					
					highlightedID = undefined;
				}
			})
		}))
		
		// Do an initial check the hash to see if there's an ID to scroll to
		observeHash();

		// Position the marginals, since there's new content.
		layoutMarginals();

		// Periodically save the chapter's edits.
		const chapterSaverID = setInterval(() => {
			$currentChapter.saveEdits();
		}, 500);

		// On cleanup, unsubscribe from everything above.
		return () => {

			window.removeEventListener('scroll', handleScroll)
			window.removeEventListener('resize', handleResize)
	
			// Stop listening to page visibility changes.
			window.removeEventListener("beforeunload", rememberPosition)
			window.removeEventListener("visibilitychange", rememberPosition)
			window.removeEventListener("pagehide", rememberPosition)
	
			// Delete the remembered position so that the next page scrolls to top.
			localStorage.removeItem("scrollposition")

			// Stop listening for hash changes
			window.removeEventListener("pushstate", observeHash)
			window.removeEventListener("popstate", observeHash)
			window.removeEventListener("hashchange", observeHash)

			// Stop observing everything on unmount
			observer.disconnect()

			// Stop saving.
			clearInterval(chapterSaverID);
		}

	});
	
	// Position the marginals on mount.
	onMount(() => layoutMarginals());

    // Keep track of the current chapter in a store to manage listeners on the chapter.
    let currentChapter = writable<Chapter>(chapter);
    let chapterChanged = () => currentChapter.set(chapter);
    $: {
        // Listen to the new edition
        $currentChapter.removeListener(chapterChanged)
        // Update the current edition.
        currentChapter.set(chapter);
		// Listen to changes on the book and chapter.
		$currentChapter.addListener(chapterChanged);
    }

	// Get the word and number to highlight from the URL
	let word: string = "";
    let number: string = "";

	// This gets called after the page is done loading. There are various things we scroll to.
	function scrollToLastLocation() {

		// In case loading changed marginal positions
		layoutMarginals();

		// If there's a word we're trying to highlight in the URL path, scroll to the corresponding match.
		if(word && number) {
			const highlights = document.getElementsByClassName("bookish-text bookish-content-highlight")
			const num = parseInt(number)
			if(highlights.length > 0 && num < highlights.length && num >= 0) {
				scrollToEyeLevel(highlights[num])
			}
		}
		// Otherwise, if there's an ID in the URL, jump to it.
		else if(highlightedID) {
			const el = document.getElementById(highlightedID as string)
			// If we found the element, remove the hash any time after a few seconds. See handleScroll for the removal logic.
			if(el) {
				scrollToEyeLevel(el)
			}
		}
		else {			
			// If we got to this page through a refresh, scroll to 
			const entries = performance.getEntriesByType("navigation");
			const position = localStorage.getItem('scrollposition');
			if(position !== null && entries.length > 0 && (entries[entries.length - 1] as PerformanceNavigationTiming).type === "reload") {
				// Scroll to the previous position, if there was one, so that refresh preserves position.
				window.scrollTo(0, parseInt(position));
			} 
			// Otherwise, just scroll to the top.
			else {
				window.scrollTo(0, 0);
			}
		}

	}

	// Prepare to render the chapter by getting some data from the chapter and book.
	$: chapterID = chapter.getChapterID();
	$: chapterNumber = $edition.getChapterNumber(chapterID);
	$: chapterSection = $edition.getChapterSection(chapterID);
	$: chapterAST = chapter.getAST();
	$: citations = chapterAST ? chapterAST.getCitations() : undefined;

    let chapterStore = writable<ChapterContext>();
    setContext<ChapterStore>(CHAPTER, chapterStore);
    $: chapterStore.set({
        chapter: chapter,
        highlightedWord: word,
        highlightedID: highlightedID,
        marginalID: marginal,
        setMarginal: (id: string | undefined) => marginal = id,
        layoutMarginals: layoutMarginals
    });

</script>

<Page afterLoaded={scrollToLastLocation} title={`${$edition.getTitle()} - ${chapter.getTitle()}`}>
    <div class="bookish-chapter">
        <Header 
            header={chapter.getTitle()}
            label="Chapter title"
            tags={$edition.getTags()}
            save={ text => chapter.setTitle(text) }
            getImage={() => chapter.getImage()}
            setImage={embed => chapter.setImage(embed)}
            print={print}
        >
            {#if !print }
                <!-- Collapse the outline if a marginal is selected. -->
                <Outline
                    slot="outline"
                    collapse={marginal !== undefined}
                    previous={$edition.getPreviousChapterID(chapterID)}
                    next={$edition.getNextChapterID(chapterID)}
                    listener={ expanded => {
                        // If the outline is being expanded, hide the marginal, otherwise leave it alone.
                        if(expanded)
                            marginal = undefined;

                        // Check if we need to hide the outline after positioning.
                        hideOutlineIfObscured();
                    }}
                />
            {/if}
            <!-- Add an editable chapter ID if in editor mode -->
            <span slot="before">
                {#if editable }
                    <span class="bookish-muted">
                        <TextEditor 
                            startText={chapter.getChapterID()} 
                            label="Chapter URL ID editor"
                            save={ 
                                // After the ID is edited, reload the page with the new URL.
                                id => chapter.setChapterID(id)?.then(() => {
                                    const ref = $edition.getRef();
                                    if(ref?.id)
                                        goto(`/write/${ref?.id}/chapter/${id}`)
                                })
                            }
                            placeholder="chapter ID"
                            valid={(newChapterID) => 
                                !/^[a-zA-Z0-9]+$/.test(newChapterID) ? "Chapter IDs must be one or more letters or numbers" :
                                chapter.getChapterID() !== newChapterID && $edition.hasChapter(newChapterID) ? "There's already a chapter that has this ID." :
                                undefined
                            }
                            saveOnExit={true}
                        />
                        <br/>
                    </span>
                {/if}
                {#if editable }
                    <Toggle on={chapter.isNumbered()} save={ on => chapter.setNumbered(on) }>
                        {#if chapterNumber !== undefined }
                            <span class="bookish-chapter-number">Chapter {chapterNumber}</span>
                        {:else}
                            <span class="bookish-muted">Unnumbered</span>
                        {/if}
                    </Toggle>
                {:else if chapterNumber !== undefined }
                    <span class="bookish-chapter-number">Chapter {chapterNumber}</span> 
                {/if}
                {#if chapterSection !== undefined }
                    <span class="bookish-section-name">&nbsp;&nbsp;{chapterSection}</span>
                {/if}
            </span>						
            <!-- If there are chapter authors, render those, otherwise use the book authors -->
            <Authors 
                slot="after"
                authors={ chapter.getAuthors() }
                inheritedAuthors={ $edition.getAuthors() }
                add={ () => chapter.addAuthor("") }
                edit={(index, text) => chapter.setAuthor(index, text) }
                remove={index => chapter.removeAuthor(index)}
            />
        </Header>
        <!-- We load this on the page but hide it; it's used as a filter for highlighing in CSS -->
        <img src={"/svg/marker.svg"} alt="highlight mark" style="display: none"/>
        <Instructions>
            Edit your chapter's title, authors, and cover image above.
            You can also change the ID of the chapter, which appears in it's URL.
            Write your chapter text below, using the many formatting options in the toolbar above to format text, add headers, lists, tables, comments, citations, footnotes, and more.
            It's okay to try things, you can always undo!
            Saves are automatic, each time you stop typing.
        </Instructions>

        <!-- Render the chapter body, passing some context -->
        {#if chapterAST }
            {#if editable }
                <BookishEditor
                    ast={chapterAST}
                    save={ node => node instanceof ChapterNode ? chapter.setAST(node) : undefined }
                    chapter={true}
                    autofocus
                    component={ChapterBody}
                    placeholder="Type here"
                /> 
            {:else}
                <ChapterBody node={chapterAST} />
            {/if}
        {:else}
            <span>Loading...</span>
        {/if}
        {#if citations && citations.size > 0 }
            {@const refs = $edition.getReferences() }
            <h1 id="references" class="bookish-header">References</h1>
            <ol>
                {#each [...citations].sort() as citationID }
                    {#if citationID in refs }
                        <li class={"bookish-reference"} id={"ref-" + citationID}>
                            <PossibleReference node={Parser.parseReference(citationID, refs[citationID], $edition)}/>
                        </li>
                    {:else}
                        <li class="bookish-error">Unknown reference: <code>{citationID}</code></li>
                    {/if}
                {/each}
            </ol>
        {/if}
    </div>
</Page>
