// src/views/page/Header.tsx
import React, { useEffect, useRef, useContext } from 'react';
import Edition from '../../models/book/Edition';
import { EmbedNode } from '../../models/chapter/EmbedNode';
import Parser from "../../models/chapter/Parser";
import Embed from '../chapter/Embed';
import ErrorMessage from '../chapter/ErrorMessage';
import BookishEditor from '../editor/BookishEditor';
import TextEditor from '../editor/TextEditor';
import { EditorContext } from './EditorContext';

type HeaderProps = {
	book: Edition;
	label: string;
	header: string;
	subtitle?: string;
	before?: React.ReactNode;
	after?: React.ReactNode;
	print?: boolean;
	tags?: string[];
	getImage: () => string | null;
	setImage: (embed: string | null) => Promise<void> | undefined
	outline: React.ReactNode;
	save?: (text: string) => Promise<void> | undefined;
}

const Header = (props: HeaderProps) => {

	const title = useRef<HTMLHeadingElement | null>(null)
	const reminder = useRef<HTMLDivElement>(null)
	const { edition: book, editable } = useContext(EditorContext)

	function updateScrollReminder() {
		if(title.current && reminder.current) {
			// If the bottom of the window is below the top of the title, hide the reminder.
			if(window.scrollY + window.innerHeight > title.current.getBoundingClientRect().top + window.scrollY)
				reminder.current.classList.add("bookish-past-title");
			else
				reminder.current.classList.remove("bookish-past-title");
		}
	}

	function addCover() { props.setImage("|||||"); }
	function removeCover() { props.setImage(null); }

    useEffect(() => {

		// When the title becomes visible or hidden, update the scroll reminder.
		const intersectionObserver = new IntersectionObserver((entries) => updateScrollReminder())
		if(title.current) intersectionObserver.observe(title.current)
		updateScrollReminder()

		return () => {
			if(title.current)
				intersectionObserver.unobserve(title.current)
		}

	}, [])

	const titleView = <>
		{props.header}
		{ props.subtitle ? <div className="bookish-subtitle">{props.subtitle}</div> : null }
	</>

	const embed = props.getImage();
	const embedNode = embed ? Parser.parseEmbed(props.book, embed) : undefined;

	return (
		<div className="bookish-chapter-header">
			{
				embedNode ?
					<div className="bookish-figure-full">
						{
							book && editable && embedNode instanceof EmbedNode ?
								<BookishEditor 
									ast={embedNode} 
									save={node => props.setImage(node.toBookdown())}
									chapter={false}
									autofocus={false}
									render={ node => <Embed node={node} />}
								/> :
								embedNode instanceof EmbedNode ? <Embed node={embedNode}/> : <ErrorMessage node={embedNode} />
						}
						{ props.print ? null : <div ref={reminder} className="bookish-scroll-reminder"></div> }
					</div> :
					// Add a bit of space to account for the lack of an image.
					<p>&nbsp;</p>
			}
			{ props.outline }
			{
				editable ?
					embedNode === undefined ?
						<button onClick={addCover}>+ cover image</button> :
						<button onClick={removeCover}>x cover image</button> :
					null
			}
			<div className="bookish-chapter-header-text">
				{ props.before }
				<h1 ref={title} className="bookish-title">
				{
					editable && props.save ? 
						<TextEditor 
							label={props.label}
							text={props.header + (props.subtitle ? ": " + props.subtitle : "")}
							placeholder="Title"
							valid={text => text.length === 0 ? "Titles have to be at least one character long." : undefined }
							save={props.save}
						/>
						: 
						titleView
				}
				</h1>
				{ props.after }
				{ props.tags ? <div>{props.tags.map((tag, index) => <span key={"tag-" + index} className="bookish-tag">{tag}</span>)}</div> : null }
			</div>
		</div>
	);

}

export default Header

// src/lib/components/page/Header.svelte
<script lang="ts">
    import EmbedNode from '$lib/models/chapter/EmbedNode';
    import Parser from "$lib/models/chapter/Parser";
    import Embed from '$lib/components/chapter/Embed.svelte';
    import ErrorMessage from '$lib/components/chapter/ErrorMessage.svelte';
    import BookishEditor from '$lib/components/editor/BookishEditor.svelte';
    import { onMount } from 'svelte';
    import TextEditor from '$lib/components/editor/TextEditor.svelte';
    import { getEdition, isEditable } from './Contexts';
    import type ErrorNode from '../../models/chapter/ErrorNode';

	export let label: string;
	export let header: string;
	export let subtitle: string | undefined = undefined;
	export let print: boolean = false;
	export let tags: string[] | undefined = undefined;
	export let getImage: (() => string | null);
	export let setImage: (embed: string | null) => Promise<void> | undefined;
	export let save: ((text: string) => Promise<void> | undefined) | null = null;

	let title: HTMLHeadingElement | null = null;
	let reminder: HTMLDivElement | null = null;

    let edition = getEdition();
    let editable = isEditable();

	function updateScrollReminder() {
		if(title && reminder) {
			// If the bottom of the window is below the top of the title, hide the reminder.
			if(window.scrollY + window.innerHeight > title.getBoundingClientRect().top + window.scrollY)
				reminder.classList.add("bookish-past-title");
			else
				reminder.classList.remove("bookish-past-title");
		}
	}

	function addCover() { if(setImage) setImage("|||||") ; }
	function removeCover() { if(setImage) setImage(null); }

    // When the title becomes visible or hidden, update the scroll reminder.
    onMount(() => {
		const intersectionObserver = new IntersectionObserver(() => updateScrollReminder());
		if(title) intersectionObserver.observe(title);
		updateScrollReminder();

        // Stop observing when unmounted.
		return () => { if(title) intersectionObserver.unobserve(title) }
	});

    // Get the embed, update when getImage function prop changes.
    let embedNode: EmbedNode | ErrorNode | undefined = undefined;
	$: {
        let embed = getImage();
        embedNode = embed ? Parser.parseEmbed($edition, embed) : undefined;
    }

</script>

<div class="bookish-chapter-header">
    {#if embedNode }
        <div class="bookish-figure-full">
            {#if edition && editable && embedNode instanceof EmbedNode}
                <BookishEditor 
                    ast={embedNode} 
                    save={node => setImage ? setImage(node.toBookdown()) : undefined }
                    chapter={false}
                    component={Embed}
                    placeholder=""
                />
            {:else if embedNode instanceof EmbedNode }
                <Embed node={embedNode}/>
            {:else}
                <ErrorMessage node={embedNode} />
            {/if}
            {#if !print }<div bind:this={reminder} class="bookish-scroll-reminder"></div>{/if}
        </div>
    {:else}
        <!-- Add a bit of space to account for the lack of an image. -->
        <p>&nbsp;</p>
    {/if}
    {#if !print}
        <slot name="outline"></slot>
    {/if}
    {#if editable }
        {#if embedNode === undefined }
            <button on:click={addCover}>+ cover image</button> 
        {:else}
            <button on:click={removeCover}>x cover image</button>
        {/if}
    {/if}
    <div class="bookish-chapter-header-text">
        <slot name="before"></slot>
        <h1 bind:this={title} class="bookish-title">
            {#if editable && save }
                <TextEditor 
                    label={label}
                    startText={header + (subtitle ? ": " + subtitle : "")}
                    placeholder="Title"
                    valid={text => text.length === 0 ? "Titles have to be at least one character long." : undefined }
                    save={save}
                />
            {:else}
                { header }
                {#if subtitle }<div class="bookish-subtitle">{subtitle}</div>{/if}
            {/if}
        </h1>
        <slot name="after"></slot>
        {#if tags }
            <div>{#each tags as tag}<span class="bookish-tag">{tag}</span>{/each}</div>
        {/if}
    </div>
</div>
