// src/views/page/Index.tsx
import React, { useContext } from 'react'
import { Link, useParams } from 'react-router-dom';

import Header from "./Header";
import Outline from './Outline';
import Page from './Page';

import Edition from '../../models/book/Edition';
import { BaseContext } from './Edition';
import Instructions from './Instructions';

const Index = (props: { book: Edition }) => {

    // What letter are we matching?
    const { letter } = useParams()
    const { base } = useContext(BaseContext)

    let book = props.book;

    let bookIndex = book.getBookIndex();

    let rows: React.ReactNode[] = [];
    let currentLetter: undefined | string = undefined;
    let letters: Record<string, boolean> = {};
    let count: undefined | number = undefined;

    // Build a list of words in alphabetical order.
    Object.keys(bookIndex).sort((a, b) => a.localeCompare(b)).forEach((word, index) => {

        // This block of code renders headers for letter groups
        let firstLetter = word.charAt(0).toLowerCase();

        // Update the letter that we're on.
        if(currentLetter !== firstLetter) {
            currentLetter = firstLetter;
            letters[currentLetter] = true;
        }

        // If this is the first letter, add an entry!
        if(letter === currentLetter) {

            if(count === undefined) {
                count = 0;
            } 
            else if(count >= 20) {
                count = 0;
                rows.push(<tr key={word}><td colSpan={2}><h2 className="bookish-header" id={"word-" + word}>{word}</h2></td></tr>)
            }

            rows.push(
                <tr key={"entry-" + index}>
                    <td>{word}</td>
                    <td>
                        {
                            // Sort the chapters by chapter number
                            Array.from(bookIndex[word])
                                .sort((a, b) => {
                                    let numberA = book.getChapterNumber(a);
                                    let numberB = book.getChapterNumber(b);
                                    if(numberA === undefined) return -1;
                                    if(numberB === undefined) return 1;
                                    return numberA - numberB;
                                })
                                // Map them to links to the first occurrence in the chapter.
                                .map(
                                    (chapterID, index) => 
                                        <span key={index}>
                                            Chapter { book.getChapterNumber(chapterID) !== undefined ? <span> {book.getChapterNumber(chapterID)}. </span> : null}<Link to={base + "/" + chapterID + "/" + word + "/0"}>{book.getChapterName(chapterID)}</Link>
                                            {index < bookIndex[word].size - 1 ? <br/> : null}
                                        </span>
                        )}
                    </td>
                </tr>
            );
            count++;
        }

    });

    return <Page>
        <Header 
            book={book}
            label="Index title"
			getImage={() => book.getImage(Edition.IndexID)}
			setImage={(embed) => book.setImage(Edition.IndexID, embed)}
            header="Index"
            tags={book.getTags()}
            outline={
                <Outline
                    previous={book.getPreviousChapterID(Edition.IndexID)}
                    next={book.getNextChapterID(Edition.IndexID)}
                />
            }
        />

        <Instructions>
            This index is created automatically.
            It's not perfect; we may add more control over it in the future.
        </Instructions>

        <p><em>This index includes all words, excluding common English words, words with apostrophes, and words ending in -ly.</em></p>

        <p>Pick a letter to browse:</p>

        <p>
            { "abcdefghijklmnopqrstuvwxyz".split("").map( 
                (symbol, index) => 
                    <span key={index} style={{display: "inline-block"}}>
                        {
                            symbol in letters && letter !== symbol ? 
                                <Link to={base + "/index/" + symbol}>{symbol}</Link> :
                                <span>
                                    {
                                        letter === symbol ? 
                                            <strong><span style={{fontSize: "200%"}}>{symbol}</span></strong> : 
                                            <span className={"bookish-muted"}>{symbol}</span>
                                    }
                                </span>
                        }
                        {
                            index < 26 - 1 ? 
                                <span>&sdot;</span> : 
                                null 
                        }
                    </span>
            )}
        </p>

        <div className="bookish-table">
            <table>
                <tbody>
                    { rows }
                </tbody>
            </table>
        </div>
    </Page>

}

export default Index

// src/lib/components/page/Index.svelte
<script lang="ts">
    import Header from "$lib/components/page/Header.svelte";
    import Outline from '$lib/components/page/Outline.svelte';
    import Page from '$lib/components/page/Page.svelte';
    import Instructions from '$lib/components/page/Instructions.svelte';
    import ChapterIDs from '$lib/models/book/ChapterID';
    import Link from "$lib/components/Link.svelte";
    import { getBase, getEdition } from "./Contexts";
    import { page } from "$app/stores";

    let edition = getEdition();
    let base = getBase();

    // What letter are we matching?
    $: letter = $page.params.letter;

    $: bookIndex = $edition.getBookIndex();

    let letters: Record<string, boolean> = {};
    // Figure out what letters have words
    $: {
        for(const word of Object.keys(bookIndex).sort((a, b) => a.localeCompare(b)))
            letters[word.charAt(0).toLocaleLowerCase()] = true;
    }

    let words: (string | true)[] = [];
    $: {
        words = [];
        let count = 0;
        Object.keys(bookIndex).sort((a, b) => a.localeCompare(b)).forEach(word => {
            const firstLetter = word.charAt(0).toLowerCase()
            if(letter === firstLetter) {
                count++;
                if(count % 20 === 0) words.push(true);
                words.push(word);
            }
        });
    } 

</script>

<Page title={`${$edition.getTitle()} - Index`}>
    <Header 
        label="Index title"
        getImage={() => $edition.getImage(ChapterIDs.IndexID)}
        setImage={(embed) => $edition.setImage(ChapterIDs.IndexID, embed)}
        header="Index"
        tags={$edition.getTags()}
    >
        <Outline
            slot="outline"
            previous={$edition.getPreviousChapterID(ChapterIDs.IndexID)}
            next={$edition.getNextChapterID(ChapterIDs.IndexID)}
        />
    </Header>

    <Instructions>
        This index is created automatically.
        It's not perfect; we may add more control over it in the future.
    </Instructions>

    <p><em>This index includes all words, excluding common English words, words with apostrophes, and words ending in -ly.</em></p>

    {#if Object.keys(letters).length === 0 }
        <p>There are no words in this book, so there's no index.</p>
    {:else}
        <p>Pick a letter to browse:</p>

        <p>
            {#each "abcdefghijklmnopqrstuvwxyz".split("") as symbol, index}
                <span style="display: inline-block">
                    {#if symbol in letters && letter !== symbol }
                        <Link to={base + "/index/" + symbol}>{symbol}</Link>
                    {:else}
                        <span>
                            {#if letter === symbol } 
                                <strong><span style="font-size: 200%">{symbol}</span></strong>
                            {:else}
                                <span class={"bookish-muted"}>{symbol}</span>
                            {/if}
                        </span>
                    {/if}
                    {#if index < 26 - 1 } 
                        <span>&sdot;</span>
                    {/if}
                </span>
            {/each}
        </p>

        <div class="bookish-table">
            <table>
                <tbody>
                    {#each words as word, index }
                        {#if word === true}
                            <tr><td colspan={2}><h2 class="bookish-header">{words[index + 1]}</h2></td></tr>
                        {:else}
                            <tr>
                                <td>{word}</td>
                                <td>
                                    <!-- Sort the chapters by chapter number -->
                                    {#each Array.from(bookIndex[word])
                                        .sort((a, b) => {
                                            let numberA = $edition.getChapterNumber(a);
                                            let numberB = $edition.getChapterNumber(b);
                                            if(numberA === undefined) return -1;
                                            if(numberB === undefined) return 1;
                                            return numberA - numberB;
                                        }) as chapterID, index }
                                        <!-- Map them to links to the first occurrence in the chapter. -->
                                        <span>
                                            Chapter {#if $edition.getChapterNumber(chapterID) !== undefined}<span> {$edition.getChapterNumber(chapterID)}. </span>{/if}<Link to={`${base}/${chapterID}?word=${word}`}>{$edition.getChapterName(chapterID)}</Link>
                                            {#if index < bookIndex[word].size - 1 }<br/>{/if}
                                        </span>
                                    {/each}
                                </td>
                            </tr>
                        {/if}
                    {/each}
                </tbody>
            </table>
        </div>
    {/if}
</Page>
