// src/views/page/Print.tsx
import React from 'react'
import Edition from '../../models/book/Edition'
import Chapter from "../chapter/Chapter"

const Print = (props: { book: Edition }) => {

    return <>
        {
            // Render all of the chapters
            props.book.getChapters().filter(chapter => !chapter.isForthcoming()).map(
                (chapter, index) => <Chapter key={index} book={props.book} chapter={chapter} print />
            )
        }
    </>

}

export default Print

// src/lib/components/page/Print.svelte
<script lang="ts">
    import { getContext } from 'svelte';
    import type Edition from '$lib/models/book/Edition';
    import Chapter from './Chapter.svelte';
    import { EDITION } from './Symbols';
    import type { Writable } from 'svelte/store';

    let edition = getContext<Writable<Edition>>(EDITION);

</script>

{#each $edition.getChapters().filter(chapter => !chapter.isForthcoming()) as chapter }
    <Chapter chapter={chapter} print />
{/each}
