// src/views/page/References.tsx
import React, { useEffect } from 'react';

import Header from "./Header";
import Outline from './Outline';
import Page from './Page';

import Parser from "../../models/Parser";
import Book from '../../models/Book';

import { renderNode } from '../chapter/Renderer'

const References = (props: { book: Book }) => {

	useEffect(() => {
	    // Always start at the top of the page.
		window.scrollTo(0, 0)
	}, [])

	const book = props.book;
	const references = book.hasReferences() ? book.getReferences() : null;
	const renderedReferences = [];

	// Otherwise, map references to a list with letter headers.
	if(references !== null) {

		renderedReferences.push(<p key="description"><em>Sorted by last name of first author.</em></p>)

		const sorted = Object.keys(references).sort();
		let letter: undefined | string = undefined;
		sorted.forEach((citationID) => {
			if(letter === undefined || citationID.charAt(0) !== letter) {
				letter = citationID.charAt(0);
				renderedReferences.push(<h2 key={"letter-" + letter} className="bookish-header" id={"references-" + letter}>{letter.toUpperCase()}</h2>);
			}
			renderedReferences.push(<p key={citationID}>{renderNode(Parser.parseReference(references[citationID], book))}</p>);
		})

	}

	return (
		<Page>
			<Header 
				book={book}
				image={book.getImage(Book.ReferencesID)} 
				header="References"
				tags={book.getTags()}
				outline={
					<Outline
						previous={book.getPreviousChapterID(Book.ReferencesID)}
						next={book.getNextChapterID(Book.ReferencesID)}
					/>
				}
			/>

			{
				book.hasReferences() ?
					renderedReferences :
					<p>This book has no references.</p>
			}
		</Page>
	);

}

export default References

// src/lib/components/page/References.svelte
<script lang="ts">
    import Header from "./Header.svelte";
    import Outline from './Outline.svelte';
    import Page from './Page.svelte';
    import Parser from "$lib/models/chapter/Parser";
    import type Edition from '$lib/models/book/Edition';
    import ConfirmButton from '$lib/components/editor/ConfirmButton.svelte';
    import ChapterIDs from '$lib/models/book/ChapterID';
    import { getContext } from "svelte";
    import BulkReferenceEditor from "./BulkReferenceEditor.svelte"
    import PossibleReference from "./PossibleReference.svelte";
    import { EDITABLE, EDITION } from "./Symbols";
    import type { Writable } from "svelte/store";

    let edition = getContext<Writable<Edition>>(EDITION);
    let editable = getContext<boolean>(EDITABLE);
    
    $: references = $edition.hasReferences() ? $edition.getReferences() : null;

	// Otherwise, map references to a list with letter headers.
	if(references !== null) {


	}

</script>

<Page title={`${$edition.getTitle()} - References`}>
    <Header 
        label="References title"
        getImage={() => $edition.getImage(ChapterIDs.ReferencesID)}
        setImage={(embed) => $edition.setImage(ChapterIDs.ReferencesID, embed)}
        header="References"
        tags={$edition.getTags()}
    >
        <Outline
            slot="outline"
            previous={$edition.getPreviousChapterID(ChapterIDs.ReferencesID)}
            next={$edition.getNextChapterID(ChapterIDs.ReferencesID)}
        />
    </Header>
    {#if editable }<BulkReferenceEditor />{/if}
    {#if references !== null }
        <p><em>Sorted by last name of first author.</em></p>

        {#each Object.keys(references).sort() as citationID }
            {@const ref = Parser.parseReference(citationID, references === null ? "" : references[citationID], $edition) }
            <!-- {#if letter === undefined || citationID.charAt(0) !== letter) {
                letter = citationID.charAt(0);
                renderedReferences.push(<h2 key={"letter-" + letter} className="bookish-header" id={"references-" + letter}>{letter.toUpperCase()}</h2>);
            } -->

            <p>
                <PossibleReference node={ref} />
                {#if editable}
                    <ConfirmButton
                        commandLabel="x"
                        confirmLabel="Confirm"
                        command={() => $edition.removeReference(citationID)}
                    />
                {/if}
            </p>
        {/each}

    {:else}
        <p>This book has no references.</p>
    {/if}
</Page>
