// src/views/page/TableOfContents.tsx
import React, { useEffect, useState, useContext } from 'react'
import { Link } from 'react-router-dom'

import Header from "./Header"
import Authors from "../chapter/Authors"
import Page from './Page'
import Parser from "../../models/chapter/Parser"
import { EmbedNode } from "../../models/chapter/EmbedNode"
import Edition from '../../models/book/Edition'
import Outline from './Outline'
import { BaseContext, EditorContext } from './Edition'
import Acknowledgements from './Acknowledgements'
import License from './License'
import Description from './Description'
import { Revisions } from './Revisions'
import Toggle from '../editor/Toggle'
import Chapter from '../../models/book/Chapter'
import TextEditor from '../editor/TextEditor'
import ConfirmButton from '../editor/ConfirmButton'
import Instructions from './Instructions'

const TableOfContentsRow = (props: { 
	image: React.ReactNode, 
	chapterID: string,
	chapter?: Chapter,
	title: string, 
	number?: number,
	annotation?: React.ReactNode, 
	forthcoming?: boolean, 
	etc?: React.ReactNode
}) => {

	const { base } = useContext(BaseContext)
	const { editable } = useContext(EditorContext)

	const chapter = props.chapter

	function moveUp() { chapter?.move(-1) }
	function moveDown() { chapter?.move(1) }

	return <>
		<tr className={props.forthcoming ? "bookish-forthcoming" : ""}>
			<td>{props.image}</td>
			<td>
				{ editable && chapter ? 
					<Toggle on={props.number !== undefined} save={ on => chapter.setNumbered(on) }>
						<div className="bookish-chapter-number">{props.number ? "Chapter " + props.number : <span className="bookish-muted">Unnumbered</span>}</div>
					</Toggle>
					:
					props.number ? 
						<div className="bookish-chapter-number">{"Chapter " + props.number}</div> : 
						null
				}
				{ props.forthcoming && !editable ?
					<span>{props.title}</span> :
					<Link to={base + "/" + props.chapterID}>{props.title}</Link>
				}
				{ props.annotation ? <small className="bookish-muted"><br/><em>{props.annotation}</em></small> : null }
			</td>
			<td>{props.etc}</td>
			{
				editable ?
					chapter ?
						<td>
							<button disabled={chapter.getPosition() === 0} onClick={moveUp}>{"↑"}</button>
							&nbsp;
							<button disabled={chapter.getPosition() === chapter.getBook().getChapterCount() - 1} onClick={moveDown}>{"↓"}</button>
							&nbsp;
							<ConfirmButton
								commandLabel="x"
								confirmLabel="Confirm"
								command={() => chapter.delete()}
							/>
						</td> 
						:
						<td></td>					
					:
					null
			}
		</tr>
	</>

}

const AddChapter = () => {

	const { edition: book } = useContext(EditorContext)
	const [ waiting, setWaiting ] = useState(false)

	function add() {
		if(book) {
			setWaiting(true)
			let add = book.addChapter();
			if(add)
				add.then(() => { setWaiting(false); })
		}
	}

	return <button disabled={waiting || book === undefined} onClick={add}>+</button>

}

const TableOfContents = (props: { edition: Edition }) => {

	const { base } = useContext(BaseContext)
	const { editable } = useContext(EditorContext)

	// Always start at the top of the page.
	useEffect(() => {
		window.scrollTo(0, 0)
	}, [])

	// Get the book being rendered.
	let edition = props.edition;

	function getProgressDescription(progress: null | number) {

		if(progress === null)
			return "";
		else if(progress === 0)
			return "";
		else if(progress < 30)
			return "; just started";
		else if(progress < 70)
			return "; halfway";
		else if(progress < 95)
			return "; almost done";
		else
			return "; done";

	}

	function getImage(embed: string | null) {

		// No image? Return null for React to render nothing.
		if(embed === null)
			return null;

		let embedNode = Parser.parseEmbed(edition, embed);
		return embedNode instanceof EmbedNode ? 
			<TableOfContentsImage embed={embedNode} /> :
			null;

	}

	// Get the chapter progress
	let progressStorage = localStorage.getItem("chapterProgress");
	let progress = progressStorage === null ?
		{} :
		JSON.parse(progressStorage)

	// Is there a colon? Let's make a subtitle
	let title = edition.getTitle();
	let subtitle = undefined;
	let colon = title.indexOf(":");
	if(colon >= 0) {
		subtitle = title.substring(colon + 1).trim();
		title = title.substring(0, colon).trim();
	}

	return <Page>
		<Header 
			book={edition}
			label="Book title"
			getImage={() => edition.getImage("cover")}
			setImage={embed => edition.setImage("cover", embed)}
			header={title}
			subtitle={subtitle}
			tags={edition.getTags()}
			after={<Authors 
				authors={edition.getAuthors()} 
				add={ () => edition.addAuthor("")}
				edit={(index, text) => text.length === 0 ? edition.removeAuthor(index) : edition.setAuthor(index, text)} 
			/>}
			outline={
				<Outline
					previous={null}
					next={edition.getNextChapterID("")}
				/>
			}
			save={text => props.edition.setTitle(text)}
		/>

		<Instructions>
			Above you can edit your book's authors, title, and cover image.
		</Instructions>

		<Description book={edition} />

		<Instructions>
			This will appear on the <Link to="/read">book browsing</Link> page and in your table of contents.
			Write an informative description of what your book is about.
		</Instructions>

		<h2 className="bookish-header" id="chapters">Chapters { editable ? <AddChapter/> : null }</h2>

		<Instructions>
			Add, remove, and reorder chapters here.
			You can add optional book sections to each chapter, toggle chapters as numbered/unnumbered or published/forthcoming.
			Click the title to edit the chapter.
		</Instructions>

		<div className="bookish-table">
			<table id="toc">
				<tbody>
					{
						edition.getChapters().map((chapter) => {

							// Get the image, chapter number, and section for rendering.
							const chapterID = chapter.getChapterID();
							const chapterAST = chapter.getAST();
							const readingTime = chapter.getReadingTime();
							const readingEstimate =
								readingTime === undefined ? "Forthcoming" :
								readingTime < 5 ? "<5 min read" :
								readingTime < 60 ? "~" + Math.floor(readingTime / 5) * 5 + " min read" :
								"~" + Math.floor(readingTime / 60) + " hour read";

							const etc = <>
								<small className="bookish-muted">
								<em>
									{ readingEstimate }
									{ !chapter.isForthcoming() && getProgressDescription(chapterID in progress ? progress[chapterID] : null) }
								</em>
								</small>
								{
									!chapter.isForthcoming() && chapterAST && chapterAST.getErrors().length > 0 ? 
										<span><br/><small className="bookish-error">{chapterAST.getErrors().length + " " + (chapterAST.getErrors().length > 1 ? "errors" : "error")}</small></span> :
										null
								}
							</>

							const section = chapter.getSection()

							return (
								<TableOfContentsRow
									key={chapterID}
									image={getImage(chapter.getImage())}
									chapter={chapter}
									chapterID={chapterID}
									number={edition.getChapterNumber(chapterID)}
									title={chapter.getTitle()}
									annotation={
										editable ?
											<TextEditor
												label={"Chapter section editor"}
												text={section ? section : ""}
												placeholder="Section"
												valid={ text => undefined }
												save={text => chapter.setSection(text) }
											/>
											:
											chapter.getSection()
									}
									forthcoming={chapter.isForthcoming()}
									etc={editable ? 
										<Toggle on={chapter.isForthcoming()} save={on => chapter.setForthcoming(on)}>
											{etc}
										</Toggle> 
										: 
										etc
									}
								/>
							)
						})
					}
					{
						edition.hasReferences() || editable ? 
							<TableOfContentsRow
								image={getImage(edition.getImage(Edition.ReferencesID))}
								chapterID={Edition.ReferencesID}
								title="References"
								annotation="Everything cited"
							/> 
							: null
					}
					{
						edition.getGlossary() && Object.keys(edition.getGlossary()).length > 0 || editable ?
							<TableOfContentsRow
								image={getImage(edition.getImage(Edition.GlossaryID))}
								chapterID={Edition.GlossaryID}
								title="Glossary"
								annotation="Definitions"
							/> 
							: null
					}
					<TableOfContentsRow
						image={getImage(edition.getImage(Edition.IndexID))}
						chapterID={Edition.IndexID}
						title="Index"
						annotation="Common words and where they are"
					/>
					<TableOfContentsRow
						image={getImage(edition.getImage(Edition.SearchID))}
						chapterID={Edition.SearchID}
						title="Search"
						annotation="Find where words occur"
					/>
					<TableOfContentsRow
						image={getImage(edition.getImage(Edition.MediaID))}
						chapterID={Edition.MediaID}
						title="Media"
						annotation="Images and video in the book"
					/>
					{
						editable ?
							<TableOfContentsRow
							image={undefined}
							chapterID="theme"
							title="Theme"
							annotation="Style the book"
						/> : null
					}
					{
						editable ?
							<TableOfContentsRow
							image={getImage(edition.getImage(Edition.UnknownID))}
							chapterID="unknown"
							title="Unknown"
							annotation="Customize bad links."
						/> : null
					}
				</tbody>
			</table>
		</div>

		<Acknowledgements book={edition} />
		<License book={edition} />

		<h2 className="bookish-header" id="print">Print</h2>

		<Instructions>
			This offers a way for readers to print the entire book as a single page.
		</Instructions>

		<p>
			Want to print this book or generate a PDF? 
			See <Link to={base + "print"}>all chapters on a single page</Link> and then print or export.
			Long books can take some time to render.
		</p>

		<h2 className="bookish-header" id="citation">Citation</h2>

		<Instructions>
			This citation is dynamically created from the current authors, title, and date.
		</Instructions>

		<p>
			{ edition.getAuthors().map(author => Parser.parseFormat(edition, author).toText()).join(", ") } ({(new Date()).getFullYear() }). <em>{edition.getTitle()}</em>. { location.protocol+'//'+location.host+location.pathname }, <em>retrieved { (new Date()).toLocaleDateString("en-US")}</em>.
		</p>

		<Revisions edition={edition} />
		
	</Page>

}

function TableOfContentsImage(props: { embed: EmbedNode }) {

	const { embed } = props;

	return <img 
		style={{width: "5em"}} 
		src={embed.getSmallURL() }
		alt={props.embed.getDescription() }
	/>

}

export default TableOfContents

// src/lib/components/page/TableOfContents.svelte
<script lang="ts">
    import Instructions from "$lib/components/page/Instructions.svelte";
    import Parser from "$lib/models/chapter/Parser";
    import TableOfContentsRow from "./TableOfContentsRow.svelte";
    import ChapterIDs from "$lib/models/book/ChapterID";
    import Page from "$lib/components/page/Page.svelte";
    import Header from "$lib/components/page/Header.svelte";
    import Outline from "$lib/components/page/Outline.svelte";
    import Link from "$lib/components/Link.svelte";
    import SubdomainEditor from "$lib/components/page/SubdomainEditor.svelte";
    import Description from "./Description.svelte";
    import Acknowledgements from "./Acknowledgements.svelte";
    import License from "$lib/components/page/License.svelte";
    import Revisions from "./Revisions.svelte";
    import Authors from "$lib/components/page/Authors.svelte";
    import TextEditor from "$lib/components/editor/TextEditor.svelte";
    import Toggle from "$lib/components/editor/Toggle.svelte";
    import { getBase, getEdition, isEditable } from "./Contexts";
    import Muted from "./Muted.svelte";

    let edition = getEdition();
	let base = getBase();
	let editable = isEditable();

	function getProgressDescription(progress: null | number) {

		if(progress === null)
			return "";
		else if(progress === 0)
			return "";
		else if(progress < 30)
			return "; just started";
		else if(progress < 70)
			return "; halfway";
		else if(progress < 95)
			return "; almost done";
		else
			return "; done";

	}

	// Get the chapter progress
	let progressStorage = typeof localStorage !== "undefined" ? localStorage.getItem("chapterProgress") : null;
	let progress = progressStorage === null ?
		{} :
		JSON.parse(progressStorage)

	// Is there a colon? Let's make a subtitle
    $: title = $edition.getTitle();
	let subtitle: string | undefined = undefined;
	$: {
    	let colon = title.indexOf(":");
        if(colon >= 0) {
            subtitle = title.substring(colon + 1).trim();
            title = title.substring(0, colon).trim();
        }
    }

    let waitingForChapter = false;

    function addChapter() {
        waitingForChapter = true;
        $edition.addChapter().then(() => waitingForChapter = false);
	}

</script>

<Page title={$edition.getTitle()}>
    <Header 
        label="Book title"
        getImage={() => $edition.getImage("cover")}
        setImage={embed => $edition.setImage("cover", embed)}
        header={title}
        subtitle={subtitle}
        tags={$edition.getTags()}
        save={text => $edition.setTitle(text)}
    >
        <svelte:fragment slot="before">
            {#if editable}
                <SubdomainEditor slot="before"/>
            {/if}
        </svelte:fragment>
        <Outline slot="outline"
            previous={null}
            next={$edition.getNextChapterID("")}
        />
        <Authors slot="after" 
            authors={$edition.getAuthors()}
            add={ () => $edition.addAuthor("")}
            edit={(index, text) => $edition.setAuthor(index, text) } 
            remove={index => $edition.removeAuthor(index)}
        />
    </Header>

    <Instructions>
        Above you can edit your book's authors, title, and cover image.
    </Instructions>

    <Description/>

    <Instructions>
        This will appear on the <Link to={base + "/read"}>book browsing</Link> page and in your table of contents.
        Write an informative description of what your book is about.
    </Instructions>

    <h2 class="bookish-header" id="chapters">Chapters {#if editable}<button disabled={waitingForChapter} on:click={addChapter}>+</button>{/if}</h2>

    <Instructions>
        Add, remove, and reorder chapters here.
        You can add optional book sections to each chapter, toggle chapters as numbered/unnumbered or published/forthcoming.
        Click the title to edit the chapter.
    </Instructions>

    <div class="bookish-table">
        <table id="toc">
            <tbody>
                {#each $edition.getChapters() as chapter }
                    {@const chapterID = chapter.getChapterID() }
                    {@const readingTime = chapter.getReadingTime() }
                    {@const readingEstimate =
                            readingTime === undefined ? "Forthcoming" :
                            readingTime < 5 ? "<5 min read" :
                            readingTime < 60 ? "~" + Math.floor(readingTime / 5) * 5 + " min read" :
                            "~" + Math.floor(readingTime / 60) + " hour read" }
                    {@const section = chapter.getSection() }
                    {@const etc = readingEstimate + (!chapter.isForthcoming() ? getProgressDescription(chapterID in progress ? progress[chapterID] : null) : "") }

                    <TableOfContentsRow
                        chapter={chapter}
                        chapterID={chapterID}
                        number={$edition.getChapterNumber(chapterID)}
                        title={chapter.getTitle()}
                        forthcoming={chapter.isForthcoming()}
                    >
                        <span slot="annotation">
                            {#if editable }
                                <TextEditor
                                    label={"Chapter section editor"}
                                    startText={section ? section : ""}
                                    placeholder="Section"
                                    valid={ () => undefined }
                                    save={text => chapter.setSection(text) }
                                />
                            {:else}
                                {#if section }{section}{/if}
                            {/if}
                        </span>
                        <span slot="etc">
                            <Muted>
                                {#if editable}
                                    <Toggle on={chapter.isForthcoming()} save={on => chapter.setForthcoming(on)}>
                                        {etc}
                                    </Toggle>
                                {:else}
                                    { etc }
                                {/if}
                            </Muted>
                        </span>
                    </TableOfContentsRow>
                {/each}
                {#if $edition.hasReferences() || editable }
                    <TableOfContentsRow
                        chapterID={ChapterIDs.ReferencesID}
                        title="References"
                    >
                        <span slot="annotation">Everything cited</span>
                    </TableOfContentsRow>
                {/if}
                {#if $edition.getGlossary() && Object.keys($edition.getGlossary()).length > 0 || editable }
                    <TableOfContentsRow
                        chapterID={ChapterIDs.GlossaryID}
                        title="Glossary"
                    > 
                        <span slot="annotation">Definitions</span>
                    </TableOfContentsRow>
                {/if}
                <TableOfContentsRow
                    chapterID={ChapterIDs.IndexID}
                    title="Index"
                > 
                    <span slot="annotation">Common words and where they are</span>
                </TableOfContentsRow>
                <TableOfContentsRow
                    chapterID={ChapterIDs.SearchID}
                    title="Search"
                > 
                    <span slot="annotation">Find where words occur</span>
                </TableOfContentsRow>

                <TableOfContentsRow
                    chapterID={ChapterIDs.MediaID}
                    title="Media"
                > 
                    <span slot="annotation">Images and video in the book</span>
                </TableOfContentsRow>
                {#if editable }
                    <TableOfContentsRow
                        chapterID="theme"
                        title="Theme"
                    > 
                        <span slot="annotation">Style the book</span>
                    </TableOfContentsRow>
                    <TableOfContentsRow
                        chapterID="unknown"
                        title="Unknown"
                    > 
                        <span slot="annotation">Customize bad links</span>
                    </TableOfContentsRow>
                {/if}
            </tbody>
        </table>
    </div>

    <Acknowledgements />
    <License />

    <h2 class="bookish-header" id="print">Print</h2>

    <Instructions>
        This offers a way for readers to print the entire book as a single page.
    </Instructions>

    <p>
        Want to print this book or generate a PDF? 
        See <Link to={base + "print"}>all chapters on a single page</Link> and then print or export.
        Long books can take some time to render.
    </p>

    <h2 class="bookish-header" id="citation">Citation</h2>

    <Instructions>
        This citation is dynamically created from the current authors, title, and date.
    </Instructions>

    <!-- Book citation -->
    <p>
        { $edition.getAuthors().map(author => Parser.parseFormat($edition, author).toText()).join(", ") } ({(new Date()).getFullYear() }). <em>{$edition.getTitle()}</em>. { location.protocol+'//'+location.host+location.pathname }, <em>retrieved { (new Date()).toLocaleDateString("en-US")}</em>.
    </p>

    <Revisions />
    
</Page>
