// src/views/page/Unknown.tsx
import React from 'react';

import Header from "./Header";
import Outline from './Outline';
import Page from './Page';
import Edition from '../../models/book/Edition'
import Instructions from './Instructions';
import ChapterIDs from '../../models/book/ChapterID';

const Unknown = (props: { book: Edition, message: React.ReactNode }) => {

	return (
		<Page>
			<Header 
				book={props.book}
				label="Unknown page title"
				getImage={() => props.book.getImage(ChapterIDs.UnknownID)}
				setImage={(embed) => props.book.setImage(ChapterIDs.UnknownID, embed)}
				header="Oops."
				outline={
					<Outline
						previous={null}
						next={null}
					/>
				}
			/>

			<Instructions>
				This page will be shown if the reader somehow ends up on a page that doesn't exist.
				You can customize the image shown.
			</Instructions>

			<p>{props.message}</p>
		</Page>
	)

}

export default Unknown;

// src/lib/components/page/Unknown.svelte
<script lang="ts">

    import Header from "./Header.svelte";
    import Outline from './Outline.svelte';
    import Page from './Page.svelte';
    import Instructions from './Instructions.svelte';
    import ChapterIDs from '$lib/models/book/ChapterID';
    import { getEdition } from "./Contexts";

    let edition = getEdition();

</script>
<Page title={`${$edition.getTitle()} - Unknown Page`}>
    <Header 
        label="Unknown page title"
        getImage={() => $edition.getImage(ChapterIDs.UnknownID)}
        setImage={embed => $edition.setImage(ChapterIDs.UnknownID, embed)}
        header="Oops."
    >    
        <Outline
            slot="outline"
            previous={null}
            next={null}
        />
    </Header>

    <Instructions>
        This page will be shown if the reader somehow ends up on a page that doesn't exist.
        You can customize the image shown.
    </Instructions>

    <slot></slot>
</Page>
