// src/lib/components/editor/ConfirmButton.svelte
<script lang="ts">
    import { onMount } from "svelte";

    export let commandLabel: string;
    export let confirmLabel: string;
    export let command: () => Promise<void> | undefined;
    
    let confirming = false;
    let executing = false;
    let timeoutID: NodeJS.Timer | undefined = undefined;
    let isMounted = false;

    onMount(() => {
        isMounted = true;
        return () => isMounted = false;
    });

    function execute() {
    
        if(!confirming && !executing) {
            confirming = true;
            timeoutID = setTimeout(() => { if(isMounted) confirming = false; }, 2000);
        } else if(confirming) {
            command()?.finally(() => {
                    if(isMounted) {
                        if(timeoutID) clearTimeout(timeoutID)
                        confirming = false;
                        executing = false;
                    }
                })
        }

    }

</script>

<button 
    disabled={executing} 
    on:click={execute} 
    class={confirming ? "bookish-editor-confirm" : ""}>
        { confirming ? confirmLabel : commandLabel }
</button>

<style>
    button.bookish-editor-confirm {
        animation: failure 100ms infinite;
    }
</style>

// src/views/editor/ConfirmButton.tsx
import React, { useEffect, useRef, useState } from "react"

const ConfirmButton = (props: { commandLabel: string, confirmLabel: string, command: () => Promise<void> | undefined }) => {

    const [ confirming, setConfirming ] = useState(false)
    const [ executing, setExecuting ] = useState(false)
    const [ timeoutID, setTimeoutID ] = useState<NodeJS.Timeout | undefined>(undefined)
    const isMounted = useRef(false)

    useEffect(() => {
        isMounted.current = true;
        return () => { isMounted.current = false }
    }, [])

    function execute() {
    
        if(!confirming && !executing) {
            setConfirming(true)
            setTimeoutID(setTimeout(() => isMounted.current ? setConfirming(false) : undefined, 2000))
        } else if(confirming) {
            props.command.call(undefined)
                ?.finally(() => {
                    if(isMounted.current) {
                        if(timeoutID) clearTimeout(timeoutID)
                        setConfirming(false)
                        setExecuting(false)
                    }
                })
        }

    }

    return <button 
        disabled={executing} 
        onClick={execute} 
        className={confirming ? "bookish-editor-confirm" : ""}>
            { confirming ? props.confirmLabel : props.commandLabel }
    </button>


}

export default ConfirmButton
