// src/lib/components/editor/InlineCodeEditor.svelte
<script lang="ts">
    import type InlineCodeNode from '$lib/models/chapter/InlineCodeNode';
    import LanguageEditor from './LanguageEditor.svelte';
    import { getCaret } from '../page/Contexts';

    export let code: InlineCodeNode;

    let caret = getCaret();
</script>

<span>
    <LanguageEditor
        language={code.getMeta()}
        edit={(lang) => $caret?.edit(code, code.withMeta(lang))}
    />
</span>

// src/views/editor/InlineCodeEditor.tsx
import { useContext } from "react";
import { InlineCodeNode } from "../../models/chapter/InlineCodeNode";
import { CaretContext, CaretContextType } from "./CaretContext";
import LanguageEditor from "./LanguageEditor";

const InlineCodeEditor = (props: {
    code: InlineCodeNode
}) => {

    const code = props.code;
    const caret = useContext<CaretContextType>(CaretContext);

    return <span>
        <LanguageEditor language={code.getMeta()} edit={lang => caret?.edit(code, code.withMeta(lang)) } />
    </span>

}

export default InlineCodeEditor;
