// src/lib/components/editor/Switch.svelte
<script lang="ts">

    export let options: string[];
    export let value: string;
    export let position: string;
    export let enabled: boolean | undefined = undefined;
    export let edit : (newValue: string) => void;

    function handleClick(event: MouseEvent) {
        const newValue = (event.currentTarget as HTMLElement).dataset.value;
        if(newValue && options.includes(newValue)) {
            edit(newValue);
        }
    }

</script>

<span class={`bookish-app-switch bookish-app-${position === "<" ? "left" : position === ">" ? "right" : "middle"}`}>
    {#each options as option }
        <button 
            class={`bookish-app-switch-option ${value === option ? "bookish-app-switch-option-selected" : ""}`} 
            data-value={option} 
            disabled={enabled === false}
            on:click|stopPropagation={handleClick}>
                {option}
        </button>
    {/each}
</span>

// src/views/editor/Switch.tsx
import React from 'react'

const Switch = (props: { 
    options: string[],
    value: string,
    position?: string,
    edit : (newValue: string) => void
}) => {

    const { value, edit, position } = props;
 
    function handleClick(event: React.MouseEvent) {

        // Don't let anything else handle the click.
        event.stopPropagation();
        const newValue = (event.currentTarget as HTMLElement).dataset.value;
        if(newValue && props.options.includes(newValue)) {
            edit.call(undefined, newValue);
        }

    }

    return <div className={`bookish-app-switch bookish-app-${position === "<" ? "left" : position === ">" ? "right" : "middle"}`}>
        {
            props.options.map((option, index) =>
                <span 
                    key={`option-${index}`} 
                    className={`bookish-app-switch-option ${value === option ? "bookish-app-switch-option-selected" : ""}`} 
                    data-value={option} 
                    onClick={handleClick}>
                        {option}
                </span>
            )
        }
    </div>

}

export default Switch;
