// src/views/app/Login.tsx
import React, { useRef, useState } from "react"
import { useAuth } from "./AuthContext"

export default function Login() {

	const emailRef = useRef<HTMLInputElement>(null)
	const { login } = useAuth()

	// Not loading by default
	const [ loading, setLoading ] = useState(false)

	// Track feedback with state
	const [ feedback, setFeedback ] = useState("")

	async function handleSubmit(e: React.FormEvent) {

		// Prevent page reload
		e.preventDefault();

		// Enter loading state, try to login and wait for it to complete, and then leave loading state.
		if(login && emailRef && emailRef.current) {
			try {
				// Give some feedback when loading.
				setLoading(true);
				await login(emailRef.current.value);
				setFeedback("Check your email for a login link.")
			} catch(err) {
				setFeedback("Hm, couldn't create an account: " + err)
			} finally {
				setLoading(false)
			}
		}

	}

	return <>

		<h1>Login to write</h1>

		<p>We'll send you an email each time to login, no password required.</p>

		<form onSubmit={handleSubmit}>
			<input autoComplete="username" type="email" placeholder="email" ref={emailRef} required disabled={loading || emailRef.current?.value.length === 0} /> <button type="submit" disabled={loading}>Login</button>
		</form>

		{ feedback && <div className="bookish-app-alert">{feedback}</div> }

	</>

}

// src/routes/(app)/login/+page.svelte
<script lang="ts">
    import { getUser } from '$lib/components/page/Contexts';
    import Feedback from '$lib/components/app/Feedback.svelte';
    import Lead from '$lib/components/app/Lead.svelte';
    import Large from '$lib/components/app/Large.svelte';
    import Paragraph from '$lib/components/app/Paragraph.svelte';
    import TextInput from '$lib/components/app/TextInput.svelte';
    import Button from '$lib/components/app/Button.svelte';

    let auth = getUser();

    let email: string = $state('');
    let loading = $state(false);
    let feedback = $state('');
    let error = $state('');

    async function handleSubmit() {
        if ($auth === undefined) return;
        // Enter loading state, try to login and wait for it to complete, and then leave loading state.
        try {
            // Give some feedback when loading.
            feedback = 'Logging in...';
            loading = true;
            await $auth.login(email);
            feedback = 'Check your email for a login link.';
        } catch (err) {
            feedback = '';
            error = "Couldn't connect to the server.";
        } finally {
            loading = false;
        }
    }
</script>

<Lead><Large>Login</Large> to write.</Lead>

<Paragraph
    >No password required to create an account. We'll email each time with a
    link.</Paragraph
>

<form onsubmit={(event) => {
        event.preventDefault();
        handleSubmit();
    }}>
    <TextInput
        bind:text={email}
        autocomplete="username"
        type="email"
        placeholder="email"
        disabled={auth === undefined || loading}
    />
    <Button
        tooltip="login into your account"
        command={handleSubmit}
        type="submit"
        disabled={auth === undefined ||
            loading ||
            !/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/.test(email)}
    >
        login
    </Button>
</form>

{#if feedback}
    <Feedback>{feedback}</Feedback>
{/if}
{#if error}
    <Feedback error>{error}</Feedback>
{/if}
