// src/views/editor/Atom.tsx
import React, { useContext } from 'react'

import { AtomNode } from '../../models/chapter/AtomNode';
import { CaretContext } from './CaretContext';

const Atom = (props: { node: AtomNode<any>, textView: React.ReactElement }) => {

    const { node, textView } = props;
    const caret = useContext(CaretContext);

    // Is the caret on this link?
    const selected = caret && caret.range && caret.range.start.node === node;
    
    function handleMouseDown(event: React.MouseEvent) {

        // Select this node
        if(caret === undefined)
            return;

        // Select this so that the view stays focused.
        caret.setCaretRange({ start: { node: node, index: 0 }, end: { node: node, index: 0 }});

        // Prevent the editor from receiving the click.
        event.stopPropagation();

    }

    return <span 
        className={`bookish-editor-atom ${selected ? "bookish-editor-atom-selected" : ""} ${caret?.focused ? "bookish-editor-atom-selected-focused" : ""}`} 
        onMouseDown={handleMouseDown}
        >
        { textView }
    </span>
    
}

export default Atom;

// src/lib/components/chapter/Atom.svelte
<script lang="ts">
    import type AtomNode from '$lib/models/chapter/AtomNode';
    import { getCaret } from '../page/Contexts';

    export let node: AtomNode<any>;

    let caret = getCaret();

    // Is the caret on this link?
    $: selected = $caret && $caret.range && $caret.range.start.node === node;
    
    function handleMouseDown() {
        // Select this so that the view stays focused.
        // caret.setCaretRange({ start: { node: node, index: 0 }, end: { node: node, index: 0 }});
    }

</script>

<!-- Prevent the editor from receiving the click. -->
<span class={`bookish-editor-atom ${selected ? "bookish-editor-atom-selected" : ""} ${$caret?.focused ? "bookish-editor-atom-selected-focused" : ""}`} on:mousedown|stopPropagation={handleMouseDown}><slot></slot></span>
