// src/views/chapter/Callout.tsx
import { CalloutNode } from "../../models/chapter/CalloutNode"
import Block from "./Block";
import renderPosition from "./renderPosition";

const Callout = (props: { node: CalloutNode }) => {

    return <div className={"bookish-callout " + renderPosition(props.node.getPosition())} data-nodeid={props.node.nodeID}>
        { props.node.getBlocks().map((element, index) => <Block node={element} key={"callout-" + index}/>)}
    </div>

}

export default Callout

// src/lib/components/chapter/Callout.svelte
<script lang="ts">
    import type CalloutNode from "$lib/models/chapter/CalloutNode"
    import Block from "./Block.svelte";
    import renderPosition from "./renderPosition";

    export let node: CalloutNode;

</script>

<div class={"bookish-callout " + renderPosition(node.getPosition())} data-nodeid={node.nodeID}>
    {#each node.getBlocks() as element }
        <Block node={element} />
    {/each}
</div>
