// src/views/chapter/ChapterBody.tsx
import { ChapterNode } from "../../models/chapter/ChapterNode"
import { ParagraphNode } from '../../models/chapter/ParagraphNode'
import Block from "./Block"
import Paragraph from './Paragraph'

const ChapterBody = (props: { node: ChapterNode, placeholder?: string }) => {

    const { node, placeholder } = props
    const errors = node.getErrors();
    const blocks = node.getBlocks();

    return <div className="bookish-chapter-body" data-nodeid={props.node.nodeID}>
        {
            errors.length === 0 ? 
                null : 
                <p>
                    <span className="bookish-error">{errors.length + " " + (errors.length > 1 ? "errors" : "error")} below</span>
                </p>
        }
        { 
            blocks.length === 1 && blocks[0] instanceof ParagraphNode && blocks[0].getFormat().isEmptyText() ?
                <Paragraph node={blocks[0]} placeholder={placeholder} /> :
                node.getBlocks().map((block, index) => <Block node={block} key={"block-" + index}/>) 
        }
    </div>

}

export default ChapterBody;

// src/lib/components/chapter/ChapterBody.svelte
<svelte:options immutable />

<script lang="ts">
    import type ChapterNode from '$lib/models/chapter/ChapterNode';
    import ParagraphNode from '$lib/models/chapter/ParagraphNode';
    import Block from './Block.svelte';
    import Paragraph from './Paragraph.svelte';
    import Problem from './Problem.svelte';

    export let node: ChapterNode;
    export let placeholder: string = '';
    export let editable: boolean = false;

    $: errors = node.getErrors();
    $: blocks = node.getBlocks();
</script>

<section class="bookish-chapter-body" data-nodeid={node.nodeID}>
    {#if editable && errors.length > 0}
        <p>
            <Problem
                >{errors.length +
                    ' ' +
                    (errors.length > 1 ? 'errors' : 'error')} below</Problem
            >
        </p>
    {/if}
    {#if blocks.length === 1 && blocks[0] instanceof ParagraphNode && blocks[0]
            .getFormat()
            .isEmptyText()}
        <Paragraph node={blocks[0]} {placeholder} />
    {:else}
        {#each node.getBlocks() as block (block.nodeID)}
            <Block node={block} />
        {/each}
    {/if}
</section>

<style>
    /* This accounts for completely empty chapters. */
    .bookish-chapter-body {
        min-height: 2em;
        min-width: 100%;
    }

    :global(.bookish-content-highlight) {
        position: relative;
    }

    /* A rectangular highlight like a highlighter marker over highlighted text */
    :global(.bookish-content-highlight:before) {
        content: '';
        z-index: -1;
        left: -0.25em;
        top: -0.5em;
        position: absolute;
        width: 100%;
        height: 2em;
        opacity: 0.7;
        padding: 0.1em 0.25em;
        transform: skew(-10deg);
        background-color: var(--bookish-highlight-color);
        filter: url(#marker);
    }
</style>
