// src/views/chapter/Citations.jsx
import React, { useContext } from 'react'
import Marginal  from './Marginal'
import Parser from '../../models/Parser'
import { renderNode } from './Renderer'
import { ChapterContext } from './Chapter'

function Citations(props) {

    const { node } = props

    const context = useContext(ChapterContext)

    let segments = [];

    // If there's no context or chapter, then render nothing.
    if(!context || !context.chapter)
        return null;

    const chapter = context.chapter
    const book = context.book

    // Sort citations numerically, however they're numbered.
    let citations = node.citations.sort((a, b) => {
        let aNumber = chapter.getCitationNumber(a);
        let bNumber = chapter.getCitationNumber(b);
        if(aNumber === null && bNumber === null) return 0;
        else if(aNumber === null && bNumber !== null) return 1;
        else if(aNumber !== null && bNumber === null) return -1;
        else return aNumber - bNumber;
    });

    // Convert each citation ID until a link.
    citations.forEach(
        (citationID, index) => {
            // Find the citation number. There should always be one,
            let citationNumber = chapter.getCitationNumber(citationID)
            if(citationNumber !== null && citationID in book.getReferences()) {
                // Add a citation.
                segments.push(
                    <sup key={index} className="bookish-citation-symbol">{citationNumber}</sup>
                );
            }
            // If it's not a valid citation number, add an error.
            else {
                segments.push(<span className="bookish-error" key={"citation-error-" + index}>Unknown reference: <code>{citationID}</code></span>)
            }

            // If there's more than one citation and this isn't the last, add a comma.
            if(citations.length > 1 && index < citations.length - 1)
                segments.push(<sup key={"citation-comma-" + index}>,</sup>);
        }
    );
    
    return <span className="bookish-citation">
        <Marginal
            id={"citation-" + citations.join("-")}
            interactor={segments}
            content={
                <span className="bookish-references">
                    {
                        citations.map((citationID, index) => {
                            let citationNumber = chapter.getCitationNumber(citationID);
                            return book.getReferences(citationID) ?
                                <span 
                                    key={index} 
                                    className="bookish-reference">
                                        <sup className="bookish-citation-symbol">{citationNumber}</sup>
                                        { renderNode(Parser.parseReference(book.getReferences()[citationID], context.book, true)) }
                                </span> :
                                null
                        })
                }
                </span>
            }
        />
    </span>

}

export default Citations

// src/lib/components/chapter/Citations.svelte
<script lang="ts">
    import Marginal  from './Marginal.svelte'
    import Parser from '$lib/models/chapter/Parser'
    import type CitationsNode from "$lib/models/chapter/CitationsNode"
    import type ChapterContext from '../page/ChapterContext'
    import Atom from './Atom.svelte';
    import { CHAPTER, EDITION } from '../page/Symbols';
    import type Edition from '$lib/models/book/Edition';
    import PossibleReference from '../page/PossibleReference.svelte';
    import { getContext } from 'svelte';
    import type { Writable } from 'svelte/store';

    export let node: CitationsNode;

    let context = getContext<ChapterContext>(CHAPTER);
    let edition = getContext<Writable<Edition>>(EDITION);

    $: chapter = context.chapter.getAST();

    // Sort citations numerically, however they're numbered.
    let citations = node.getMeta().sort((a, b) => {
        if(chapter === undefined) return 0;
        let aNumber = chapter.getCitationNumber(a);
        let bNumber = chapter.getCitationNumber(b);
        if(aNumber === null) {
            if(bNumber === null) return 0;
            else return 1;
        }
        else {
            if(bNumber === null) return -1;
            else return aNumber - bNumber;
        }
    });

</script>

<Atom {node}>
    {#if chapter }
        <span class="bookish-citation"  data-nodeid={node.nodeID}>
            <Marginal id={"citation-" + citations.join("-")}>
                <slot name="interactor">
                    {#each citations as citationID, index}
                        {@const citationNumber = chapter.getCitationNumber(citationID) }
                        {#if citationNumber !== null && citationID in $edition.getReferences()}
                            <sup class="bookish-citation-symbol">{citationNumber}</sup>
                        {:else}
                            <span class="bookish-error">Unknown reference: <code>{citationID}</code></span>
                        {/if}
                        {#if citations.length > 1 && index < citations.length - 1 }<sup>,</sup>{/if}
                    {:else}
                        <sup class="bookish-citation-symbol">{"\u2014"}</sup>            
                    {/each}
                </slot>
                <slot name="content">
                    <span class="bookish-references">
                        {#each citations as citationID }
                            {@const citationNumber = chapter.getCitationNumber(citationID) }
                            {@const ref = $edition.getReference(citationID) }
                            {#if ref }
                                <span class="bookish-reference">
                                    <sup class="bookish-citation-symbol">{citationNumber}</sup>
                                    <PossibleReference node={Parser.parseReference(citationID, ref, $edition, true)}/>
                                </span>
                            {/if}
                        {/each}
                    </span>
                </slot>
            </Marginal>
        </span>
    {:else}
        <sup class="bookish-error">Citations not allowed in non-chapters</sup>
    {/if}
</Atom>
