// src/views/chapter/Citations.tsx
import React, { useContext, useEffect } from 'react'
import Marginal  from './Marginal'
import Parser from '../../models/chapter/Parser'
import { CitationsNode } from "../../models/chapter/CitationsNode"
import { ChapterContext, ChapterContextType } from './ChapterContext'
import Atom from '../editor/Atom'
import renderReference from './renderReference'

const Citations = (props: {node: CitationsNode}) => {

    const { node } = props

    const context = useContext<ChapterContextType>(ChapterContext);

    const segments: React.ReactNode[] = [];

    const chapter = context.chapter?.getAST();
    const book = context.book;

    // If there's no context or chapter, then render nothing.
    if(book === undefined || chapter === undefined)
        return <></>;

    // Sort citations numerically, however they're numbered.
    let citations = node.getMeta().sort((a, b) => {
        let aNumber = chapter.getCitationNumber(a);
        let bNumber = chapter.getCitationNumber(b);
        if(aNumber === null) {
            if(bNumber === null) return 0;
            else return 1;
        }
        else {
            if(bNumber === null) return -1;
            else return aNumber - bNumber;
        }
    });

    // Convert each citation ID until a link.
    citations.forEach(
        (citationID, index) => {
            // Find the citation number. There should always be one,
            let citationNumber = chapter.getCitationNumber(citationID)
            if(citationNumber !== null && citationID in book.getReferences()) {
                // Add a citation.
                segments.push(
                    <sup key={index} className="bookish-citation-symbol">{citationNumber}</sup>
                );
            }
            // If it's not a valid citation number, add an error.
            else {
                segments.push(<span className="bookish-error" key={"citation-error-" + index}>Unknown reference: <code>{citationID}</code></span>)
            }

            // If there's more than one citation and this isn't the last, add a comma.
            if(citations.length > 1 && index < citations.length - 1)
                segments.push(<sup key={"citation-comma-" + index}>,</sup>);
        }
    );

    // Render empty citation list as an m-dash.
    if(citations.length === 0)
        segments.push(<sup className="bookish-citation-symbol" key="empty">{"\u2014"}</sup>);

    // Position the marginals on every render.
    useEffect(() => {
        if(context && context.layoutMarginals) {
            context.layoutMarginals();
        }
    });

    return <Atom
        node={node}
        textView={
            <span className="bookish-citation"  data-nodeid={props.node.nodeID}>
                <Marginal
                    id={"citation-" + citations.join("-")}
                    interactor={<>{segments}</>}
                    content={
                        <span className="bookish-references">
                            {
                                book ?
                                    citations.map((citationID, index) => {
                                        let citationNumber = chapter.getCitationNumber(citationID);
                                        let ref = book.getReference(citationID);
                                        return ref ?
                                            <span 
                                                key={index} 
                                                className="bookish-reference">
                                                    <sup className="bookish-citation-symbol">{citationNumber}</sup>
                                                    { renderReference(Parser.parseReference(citationID, ref, book, true)) }
                                            </span> :
                                            null
                                    }) :
                                null
                        }
                        </span>
                    }
                />
            </span>
        }
        />;

}

export default Citations

// src/lib/components/chapter/Citations.svelte
<script lang="ts">
    import Marginal  from './Marginal.svelte'
    import Parser from '$lib/models/chapter/Parser'
    import type CitationsNode from "$lib/models/chapter/CitationsNode"
    import Atom from './Atom.svelte';
    import { getChapter, getEdition } from '../page/Contexts';
    import PossibleReference from '../page/PossibleReference.svelte';
    import { afterUpdate } from 'svelte';

    export let node: CitationsNode;

    let chapter = getChapter();
    let edition = getEdition();

    $: chapterNode = $chapter?.chapter.getAST();

    // Sort citations numerically, however they're numbered.
    $: citations = node.getMeta().sort((a, b) => {
        if(chapterNode === undefined) return 0;
        let aNumber = chapterNode.getCitationNumber(a);
        let bNumber = chapterNode.getCitationNumber(b);
        if(aNumber === null) {
            if(bNumber === null) return 0;
            else return 1;
        }
        else {
            if(bNumber === null) return -1;
            else return aNumber - bNumber;
        }
    });

    // Position the marginals on every render.
    afterUpdate(() => $chapter?.layoutMarginals());

</script>

<Atom {node}>
    {#if chapterNode }
        <span class="bookish-citation"  data-nodeid={node.nodeID}>
            <Marginal id={"citation-" + citations.join("-")}>
                <svelte:fragment slot="interactor">
                    {#each citations as citationID, index}
                        {@const citationNumber = chapterNode?.getCitationNumber(citationID) }
                        {#if citationNumber && citationID in $edition.getReferences()}
                            <sup class="bookish-citation-symbol">{citationNumber}</sup>
                        {:else}
                            <span class="bookish-error">Unknown reference: <code>{citationID}</code></span>
                        {/if}
                        {#if citations.length > 1 && index < citations.length - 1 }<sup>,</sup>{/if}
                    {:else}
                        <sup class="bookish-citation-symbol">{"\u2014"}</sup>            
                    {/each}
                </svelte:fragment>
                <span slot="content" class="bookish-references">
                    {#each citations as citationID }
                        {@const citationNumber = chapterNode?.getCitationNumber(citationID) }
                        {@const ref = $edition.getReference(citationID) }
                        {#if citationNumber && ref }
                            <span class="bookish-reference">
                                <sup class="bookish-citation-symbol">{citationNumber}</sup>
                                <PossibleReference node={Parser.parseReference(citationID, ref, $edition, true)}/>
                            </span>
                        {/if}
                    {/each}
                </span>
            </Marginal>
        </span>
    {/if}
</Atom>
