// src/views/chapter/Comment.tsx
import { useContext, useEffect } from 'react'
import { CommentNode } from '../../models/chapter/CommentNode'
import Atom from '../editor/Atom';
import { ChapterContext } from './ChapterContext';
import Marginal from './Marginal';

import CommentIcon from "../../assets/svg/comment.svg";
import Format from './Format';
import { EditorContext } from '../page/EditorContext';
import { CaretContext } from '../editor/CaretContext';

const Comment = (props: { node: CommentNode }) => {

    const comment = props.node;
    const { chapter } = useContext(ChapterContext);
    const { editable } = useContext(EditorContext);
    const context = useContext(ChapterContext);
    const chapterNode = chapter?.getAST();

    const caret = useContext(CaretContext);

    useEffect(() => {
        if(context && context.layoutMarginals) {
            context.layoutMarginals();
        }
    });

    const focused = caret && caret.range && chapter && comment.contains(caret.range.start.node);

    return <Atom
        node={comment}
        textView={
            editable ?
            <Marginal 
                id={"comment-" + (chapterNode === undefined ? "?" : chapterNode.getComments().indexOf(comment))}
                interactor={<span className="bookish-comment-symbol"><CommentIcon/></span>}
                content={<span className={`bookish-app-comment ${focused ? "bookish-app-comment-focused" : ""}`}><Format node={comment.getMeta()} placeholder="comment"/></span>}
            />
            :
            <></>
        }
    />;

}

export default Comment

// src/lib/components/chapter/Comment.svelte
<script lang="ts">
    import type CommentNode from '$lib/models/chapter/CommentNode'
    import Atom from './Atom.svelte';
    import Marginal from './Marginal.svelte';
    import Format from './Format.svelte';
    import { EDITABLE, getChapter } from '../page/Contexts';
    import { getCaret } from '../page/Contexts';
    import { getContext } from 'svelte';
    import ToolbarIcon from '../editor/ToolbarIcon.svelte';

    export let node: CommentNode;
    
    let chapter = getChapter();
    let editable = getContext<boolean>(EDITABLE);
    let caret = getCaret();
    $: chapterNode = $chapter.chapter.getAST();

    $: focused = $caret && $caret.range && node.contains($caret.range.start.node);

</script>

<Atom {node}>
    {#if editable}
        <Marginal id={"comment-" + (chapterNode === undefined ? "?" : chapterNode.getComments().indexOf(node))}>
            <span slot="interactor" class="bookish-comment-symbol">
                <ToolbarIcon name="comment.svg"/>
            </span>
            <span slot="content" class={`bookish-app-comment ${focused ? "bookish-app-comment-focused" : ""}`}>
                <Format node={node.getMeta()} placeholder="comment"/>
            </span>
        </Marginal>
    {/if}
</Atom>
