// src/views/chapter/Definition.tsx
import { useContext, useEffect } from 'react'
import Marginal  from './Marginal'
import Parser from '../../models/chapter/Parser'
import { DefinitionNode } from "../../models/chapter/DefinitionNode"
import { ChapterContext, ChapterContextType } from './ChapterContext'
import Text from './Text'
import Format from './Format'

const Definition = (props: { node: DefinitionNode}) => {

    const { node } = props
    const glossaryID = node.getMeta();
    const phrase = node.getText();

    const context = useContext<ChapterContextType>(ChapterContext);

    // If there's no context, render nothing.
    if(!context || !context.book)
        return <></>

    // Find the definition.
    let glossary = context.book.getGlossary();
    let entry = glossary[glossaryID];

    // Position the marginals on every render.
    useEffect(() => {
        if(context && context.layoutMarginals) {
            context.layoutMarginals();
        }
    });

    const phraseView = <Text node={phrase}/>
    const marginalView = 
        // Error if there's no corresponding entry.
        <span className={`bookish-definition ${entry === undefined ? "bookish-error" : ""}`} data-nodeid={props.node.nodeID}>
            <Marginal
                id={"glossary-" + glossaryID}
                interactor={phraseView}
                content={
                    <span className="bookish-definition-entry">
                        { 
                            entry === undefined ? 
                                <span className="bookish-error">Unknown glossary entry "{ glossaryID }"</span> :
                                <>
                                    <strong className="bookish-definition-entry-phrase">{entry.phrase}</strong>: { <Format node={Parser.parseFormat(context.book, entry.definition)} key="definition" /> }
                                    { entry.synonyms && entry.synonyms.length > 0 ? <span className="bookish-definition-entry-synonyms"><br/><br/>{entry.synonyms.join(", ")}</span> : null }
                                </>
                        }
                    </span>
                }
            />
        </span>;

    return marginalView;

}

export default Definition

// src/lib/components/chapter/Definition.svelte
<script lang="ts">
    import Parser from '$lib/models/chapter/Parser';
    import type DefinitionNode from '$lib/models/chapter/DefinitionNode';
    import Text from './Text.svelte';
    import Format from './Format.svelte';
    import Marginal from './Marginal.svelte';
    import Problem from './Problem.svelte';
    import { getChapter, getEdition } from '../page/Contexts';
    import { afterUpdate } from 'svelte';

    export let node: DefinitionNode;

    let edition = getEdition();
    let chapter = getChapter();

    // Find the definition.
    $: glossaryID = node.getMeta();
    $: phrase = node.getText();
    $: glossary = $edition.getGlossary();
    $: entry = glossary[glossaryID];

    // Position the marginals on every render.
    afterUpdate(() => $chapter?.layoutMarginals());
</script>

<!-- Error if there's no corresponding entry. -->
<span class="bookish-definition" data-nodeid={node.nodeID}>
    <Marginal {node} id={'glossary-' + glossaryID}>
        <Text slot="interactor" node={phrase} /><span
            slot="content"
            class="bookish-definition-entry"
            >{#if entry === undefined}<Problem
                    >Unknown glossary entry "{glossaryID}"</Problem
                >{:else}<strong class="bookish-definition-entry-phrase"
                    >{entry.phrase}</strong
                >: <Format
                    node={Parser.parseFormat($edition, entry.definition)}
                />{#if entry.synonyms && entry.synonyms.length > 0}<span
                        class="bookish-definition-entry-synonyms"
                        ><br /><br />{entry.synonyms.join(', ')}</span
                    >{/if}{/if}</span
        >
    </Marginal>
</span>

<style>
    .bookish-definition :global(.bookish-marginal-interactor) {
        border-bottom: 2px solid var(--bookish-link-color);
    }

    .bookish-definition-entry {
        display: block;
        padding-left: 0.75rem;
        font-size: var(--bookish-small-font-size);
        line-height: var(--bookish-paragraph-line-height-tight);
        text-align: left;
        margin-left: 0.25rem;
        margin-bottom: 1rem;
        background: linear-gradient(
                to right,
                var(--bookish-link-color) 0px,
                var(--bookish-link-color) 2px,
                transparent 2px
            )
            no-repeat right;
    }

    .bookish-definition-entry .bookish-definition-entry-synonyms {
        color: var(--bookish-muted-color);
        font-style: italic;
    }
</style>
