// src/views/chapter/InlineCode.tsx
import { useContext } from 'react'
import Code from './Code'
import { InlineCodeNode } from "../../models/chapter/InlineCodeNode"
import { EditorContext } from '../page/EditorContext'
import Text from './Text'

const InlineCode = (props: { node: InlineCodeNode }) => {

    const { node } = props

    const editable = useContext(EditorContext);

    const editableView = <span className="bookish-code bookish-code-inline hljs" data-nodeid={node.nodeID}><Text node={node.getText()}/></span>;
    const staticView = <Code editable={false} inline={true} language={node.getMeta()} nodeID={node.getText().nodeID}>{node.getText().getText()}</Code>;

    return editable ? editableView : staticView;

}

export default InlineCode

// src/lib/components/chapter/InlineCode.svelte
<script lang="ts">
    import type InlineCodeNode from "$lib/models/chapter/InlineCodeNode";
    import { getContext } from "svelte";
    import { EDITABLE } from "../page/Contexts";
    import Code from './Code.svelte'
    import Text from './Text.svelte'

    export let node: InlineCodeNode;

    let editable = getContext(EDITABLE);

</script>

{#if editable }
    <span class="bookish-code bookish-code-inline hljs" data-nodeid={node.nodeID}><Text node={node.getText()}/></span>
{:else}
    <Code editable={false} inline={true} language={node.getMeta()} nodeID={node.getText().nodeID}>{node.getText().getText()}</Code>
{/if}
