// src/views/chapter/Marginal.tsx
import React, { useEffect, useState, useContext, ReactElement } from 'react';
import { ChapterContext } from './ChapterContext';

import { isMobile, watchMobile } from '../util/isMobile';

 const Marginal = (props: { id: string, content: ReactElement, interactor: ReactElement }) => {

	let [ hovered, setHovered ] = useState(false)
	const context = useContext(ChapterContext)

	// If there's no marginal selected or this is different from the current selection, this is hidden.
	function isHidden() { 
		return context.marginalID === null || context.marginalID !== props.id
	}

	function toggle() {

		if(context.setMarginal) {
			if(isMobile() && isHidden())
				context.setMarginal(props.id);
			// Otherwise, deselect.
			else
				context.setMarginal(undefined);
		}

	}

	const handleEnter = () => setHovered(true)
	const handleExit = () => setHovered(false)

	useEffect(() => {

		const mediaWatch = watchMobile()
		mediaWatch.addEventListener("change", toggle)

		return () => {
			mediaWatch.removeEventListener("change", toggle)
		}

	}, [])

	return (
		<span>
			<span 
				className={"bookish-marginal-interactor" + (hovered ? " bookish-marginal-hovered" : "") + (isHidden() ? "" : " bookish-marginal-selected")} 
				onClick={toggle} 
				onMouseEnter={handleEnter} 
				onMouseLeave={handleExit}
			>
				{props.interactor}
			</span>
			<span className={"bookish-marginal" + (isHidden() ? " bookish-marginal-hidden" : "") + (hovered ? " bookish-marginal-hovered" : "")} onClick={toggle} onMouseEnter={handleEnter} onMouseLeave={handleExit}>
				{props.content}
			</span>
		</span>
	)
}

export default Marginal

// src/lib/components/chapter/Marginal.svelte
<script lang="ts">
    import { isMobile, watchMobile } from '$lib/util/isMobile';
    import { onMount } from 'svelte';
    import { getChapter } from '../page/Contexts';

    export let id: string;

	let hovered = false;
	let context = getChapter();

	// If there's no marginal selected or this is different from the current selection, this is hidden.
	function isHidden() { 
		return $context.marginalID === null || $context.marginalID !== id
	}

	function toggle() {

		if($context.setMarginal) {
			if(isMobile() && isHidden())
				$context.setMarginal(id);
			// Otherwise, deselect.
			else
				$context.setMarginal(undefined);
		}

	}

	function handleEnter() { hovered = true }
	function handleExit() { hovered = false }

    onMount(() => {
		const mediaWatch = watchMobile();
		mediaWatch.addEventListener("change", toggle)

		return () => mediaWatch.removeEventListener("change", toggle);
	});

</script>

<span 
    class={"bookish-marginal-interactor" + (hovered ? " bookish-marginal-hovered" : "") + (isHidden() ? "" : " bookish-marginal-selected")} 
    on:click={toggle} 
    on:mouseenter={handleEnter} 
    on:mouseleave={handleExit}
>
    <slot name="interactor"></slot>
</span>
<span 
    class={"bookish-marginal" + (isHidden() ? " bookish-marginal-hidden" : "") + (hovered ? " bookish-marginal-hovered" : "")} 
    on:click={toggle} 
    on:mouseenter={handleEnter} 
    on:mouseleave={handleExit}
>
    <slot name="content"></slot>
</span>
