// src/views/chapter/Table.jsx
import React from 'react'

import { renderNode, renderPosition } from './Renderer'

function Table(props) {

    const { node, key } = props

    return <div key={key} className={"bookish-figure " + renderPosition(node.position)}>
        {/* Make the table responsive for small screens */}
        <div className="bookish-table">
            <table>
                <tbody>
                {
                    node.rows.map((row, index) => 
                        <tr key={"row-" + index}>
                            {
                                row.length === 1 ?
                                    [<td key={"cell-" + index} colSpan={node.rows.reduce((max, row) => Math.max(row.length, max), 0)}>{renderNode(row[0], "cell-" + index)}</td>] :
                                    row.map((cell, index) => <td key={"cell-" + index}>{renderNode(cell, "cell-" + index)}</td>)
                            }
                        </tr>
                    )
                }
                </tbody>
            </table>
        </div>
        <div className="bookish-figure-caption">{renderNode(node.caption)}</div>
    </div>

}

export default Table

// src/lib/components/chapter/Table.svelte
<script lang="ts">
    import type TableNode from "$lib/models/chapter/TableNode"
    import Format from './Format.svelte'
    import renderPosition from "./renderPosition"

    export let node: TableNode;

    let rows = node.getRows();
    let caption = node.getCaption();

</script>

<div class={"bookish-figure " + renderPosition(node.getPosition())} data-nodeid={node.nodeID}>
    <div class="bookish-table">
        <table>
            <tbody>
            {#each rows as row }
                <tr>
                    {#if row.length === 1 }
                        <td colspan={rows.reduce((max, row) => Math.max(row.length, max), 0)}><Format node={row[0]}/></td>
                    {:else}
                        {#each row as cell }
                            <td><Format node={cell}/></td>
                        {/each}
                    {/if}
                </tr>
            {/each}
            </tbody>
        </table>
    </div>
    {#if caption !== undefined}
        <div class="bookish-figure-caption"><Format node={caption} placeholder="caption"/></div>
    {/if}
</div>
