// src/views/editor/CalloutEditor.tsx
import { useContext } from 'react';
import { CalloutNode } from "../../models/chapter/CalloutNode"
import { Position } from '../../models/chapter/Position';
import { CaretContext, CaretContextType } from './CaretContext';
import PositionEditor from "./PositionEditor";

const CalloutEditor = (props: {
    callout: CalloutNode
}) => {

    const callout = props.callout;
    const caret = useContext<CaretContextType>(CaretContext);

    return <>
        <PositionEditor 
            value={callout.getPosition()} 
            edit={(position: string) => caret?.edit(callout, callout.withPosition(position as Position))}
        />
    </>

}

export default CalloutEditor;

// src/lib/components/editor/CalloutEditor.svelte
<script lang="ts">
    import type CalloutNode from '$lib/models/chapter/CalloutNode';
    import PositionEditor from './PositionEditor.svelte';
    import { getCaret } from '../page/Contexts';

    export let callout: CalloutNode;

    let caret = getCaret();
</script>

<PositionEditor
    value={callout.getPosition()}
    edit={(position) => $caret?.edit(callout, callout.withPosition(position))}
/>
