// src/views/editor/CaptionedCodeEditor.tsx
import { useContext } from "react";
import { CodeNode } from "../../models/chapter/CodeNode";
import { Position } from "../../models/chapter/Position";
import { CaretContext, CaretContextType } from "./CaretContext";
import LanguageEditor from "./LanguageEditor";
import PositionEditor from "./PositionEditor";
import Switch from "./Switch";

const CaptionedCodeEditor = (props: {
    code: CodeNode
}) => {

    const code = props.code;
    const caret = useContext<CaretContextType>(CaretContext);

    return <span>
        <PositionEditor
            value={code.getPosition()}
            edit={(value: string) => caret?.edit(code, code.withPosition(value as Position)) }
        />
        <LanguageEditor language={code.getLanguage()} edit={lang => caret?.edit(code, code.withLanguage(lang)) } />
        { code.getLanguage() !== "python" ? null : 
            <Switch
                options={["executable", "read only"]}
                value={code.isExecutable() ? "executable" : "read only"}
                position=">"
                edit={(value: string) => caret?.edit(code, code.withExecutable(value === "executable")) }
            />
        }

    </span>

}

export default CaptionedCodeEditor;

// src/lib/components/editor/CaptionedCodeEditor.svelte
<script lang="ts">
    import type CodeNode from "$lib/models/chapter/CodeNode";
    import LanguageEditor from "./LanguageEditor.svelte";
    import PositionEditor from "./PositionEditor.svelte";
    import Switch from "$lib/components/editor/Switch.svelte";
    import { CARET } from "../page/Symbols";
    import type CaretContext from "./CaretContext";
    import { getContext } from "svelte";

    export let code: CodeNode;

    let caret = getContext<CaretContext>(CARET);

</script>
<span>
    <PositionEditor
        value={code.getPosition()}
        edit={value => caret?.edit(code, code.withPosition(value)) }
    />
    <LanguageEditor language={code.getLanguage()} edit={lang => caret?.edit(code, code.withLanguage(lang)) } />
    {#if code.getLanguage() === "python"}
        <Switch
            options={["executable", "read only"]}
            value={code.isExecutable() ? "executable" : "read only"}
            position=">"
            edit={value => caret?.edit(code, code.withExecutable(value === "executable")) }
        />
    {/if}
</span>
