// src/views/editor/CitationsEditor.tsx
import { useContext } from "react";
import { CitationsNode } from "../../models/chapter/CitationsNode";
import { ChapterContext, ChapterContextType } from "../chapter/ChapterContext";
import Select, { MultiValue } from 'react-select';
import { CaretContext } from "./CaretContext";

const CitationsEditor = (props: {
    citations: CitationsNode
}) => {

    const citations = props.citations;
    const context = useContext<ChapterContextType>(ChapterContext);
    const book = context.book;
    const caret = useContext(CaretContext);

    if(book === undefined)
        return null;

    function handleCitationsChange(newValue: MultiValue<{value: string, label: string}>) {

        let newCitations = newValue.map(val => val.value);
        caret?.edit(citations, citations.withMeta(newCitations));

    }

    return <span>
        <Select 
            isMulti 
            className="bookish-editor-select"
            classNamePrefix="bookish-editor-select"
            placeholder="Choose one or more citations."
            value={ citations.getMeta().map(val => { return { value: val, label: val }; }) }
            options={Object.keys(book.getReferences()).sort().map(citationID => { return {value: citationID, label: citationID }; })} 
            onChange={handleCitationsChange}
        />
        {
            citations.getMeta().length === 0 ?
                <span className="bookish-editor-note bookish-editor-note-error">Choose at least one citation.</span> :
                null
        }
    </span>;

}

export default CitationsEditor;

// src/lib/components/editor/CitationsEditor.svelte
<script lang="ts">
    import type CitationsNode from "$lib/models/chapter/CitationsNode";

    export let citations: CitationsNode;

    // let book = getContext<Book>(BOOK);
    // let caret = getContext(CaretContext)(CARET);

    // function handleCitationsChange(newValue: MultiValue<{value: string, label: string}>) {

    //     let newCitations = newValue.map(val => val.value);
    //     caret?.edit(citations, citations.withMeta(newCitations));

    // }

</script>

<span>
    TBD
    <!-- TBD -->
    <!-- <Select 
        isMulti 
        class="bookish-editor-select"
        classNamePrefix="bookish-editor-select"
        placeholder="Choose one or more citations."
        value={ citations.getMeta().map(val => { return { value: val, label: val }; }) }
        options={Object.keys(book.getReferences()).sort().map(citationID => { return {value: citationID, label: citationID }; })} 
        onChange={handleCitationsChange}
    />
    {
        citations.getMeta().length === 0 ?
            <span className="bookish-editor-note bookish-editor-note-error">Choose at least one citation.</span> :
            null
    } -->
</span>
