// src/views/editor/DefinitionEditor.tsx
import { ChangeEvent, useContext, useRef } from "react";
import { DefinitionNode } from "../../lib/models/chapter/DefinitionNode";
import { ChapterContext, ChapterContextType } from "../../lib/components/page/ChapterContext";
import { CaretContext } from "../../lib/components/editor/CaretContext";

const DefinitionEditor = (props: {
    definition: DefinitionNode
}) => {

    const definition = props.definition;
    const context = useContext<ChapterContextType>(ChapterContext);
    const book = context.book;
    const caret = useContext(CaretContext);
    const selectRef = useRef<HTMLSelectElement>(null);
 
    // If there's no context, render nothing.
    if(!context || !context.book)
        return <></>

    const glossary = context.book.getGlossary();

    if(book === undefined)
        return null;

    function handleChange(e: ChangeEvent<HTMLSelectElement>) {
        caret?.edit(definition, definition.withMeta(e.target.value))
    }

    // Sort the glossary entries by phrase
    const entries = Object.keys(glossary).map(key => { return { glossaryID: key, phrase: glossary[key].phrase }; }).sort((a, b) => a.phrase.localeCompare(b.phrase));
    
    const refID = book.getRef()?.id;
    const glossaryLink = `/write/${refID}/glossary`;

    return <span>
        <select 
            ref={selectRef} 
            tabIndex={0} 
            value={definition.getMeta()} 
            onChange={handleChange}
        >
            <option value=""></option>
            { entries.map((entry, index) => <option key={index} value={entry.glossaryID}>{entry.phrase}</option>)}
        </select>
        {
            definition.getMeta() in glossary ?
                null :
                <span className="bookish-editor-error">Choose a <a href={glossaryLink}>glossary</a> entry.</span>
        }
    </span>;

}

export default DefinitionEditor;

// src/lib/components/editor/DefinitionEditor.svelte
<script lang="ts">
    import type DefinitionNode from "$lib/models/chapter/DefinitionNode";
    import type CaretContext from "$lib/components/editor/CaretContext";
    import { getContext } from "svelte";
    import { CARET, EDITION } from "../page/Symbols";
    import type Edition from "$lib/models/book/Edition";

    export let definition: DefinitionNode;

    let edition = getContext<Edition>(EDITION);
    let caret = getContext<CaretContext>(CARET);
 
    $: glossary = edition.getGlossary();

    function handleChange(event: Event) {
        const target = event.target as HTMLSelectElement;
        caret?.edit(definition, definition.withMeta(target.value))
    }

    // Sort the glossary entries by phrase
    $: entries = Object.keys(glossary).map(key => { return { glossaryID: key, phrase: glossary[key].phrase }; }).sort((a, b) => a.phrase.localeCompare(b.phrase));    
    $: refID = edition.getRef()?.id;
    $: glossaryLink = `/write/${refID}/glossary`;

</script>

<span>
    <select 
        tabindex={0} 
        value={definition.getMeta()} 
        on:change={handleChange}
    >
        <option value=""></option>
        {#each entries as entry}<option value={entry.glossaryID}>{entry.phrase}</option>{/each}
    </select>
    {#if !(definition.getMeta() in glossary)}
        <span class="bookish-editor-error">Choose a <a href={glossaryLink}>glossary</a> entry.</span>
    {/if}
</span>
