// src/views/editor/PositionEditor.tsx
import React from 'react'
import Switch from './Switch';

const PositionEditor = (props: { 
    value: string,
    edit : (newValue: string) => void
}) => {

    return <Switch
        options={["<", "|", ">"]}
        value={props.value}
        edit={props.edit} 
    />

}

export default PositionEditor;

// src/lib/components/editor/PositionEditor.svelte
<script lang="ts">
    import type Position from "$lib/models/chapter/Position";
    import Switch from "./Switch.svelte";

    export let value: string;
    export let edit : (newValue: Position) => void;

    function editAsString(newValue: string) {
        edit(newValue as Position);
    }

</script>

<Switch
    options={["<", "|", ">"]}
    value={value}
    edit={editAsString} 
/>
