// src/views/editor/QuoteEditor.tsx
import React from 'react';
import { QuoteNode } from "../../models/chapter/QuoteNode"
import { Position } from '../../models/chapter/Position';
import PositionEditor from "./PositionEditor";

const QuoteEditor = (props: {
    quote: QuoteNode
}) => {

    const quote = props.quote;

    // TOOD Immutable: setPosition
    return <>
        <PositionEditor value={quote.getPosition()} edit={(position: string) => quote.withPosition(position as Position)} />
    </>

}

export default QuoteEditor;

// src/lib/components/editor/QuoteEditor.svelte
<script lang="ts">
    import type QuoteNode from "$lib/models/chapter/QuoteNode"
    import { getCaret } from "../page/Contexts";
    import PositionEditor from "./PositionEditor.svelte";

    export let quote: QuoteNode;

    let caret = getCaret();
    
</script>

<PositionEditor value={quote.getPosition()} edit={position => $caret?.edit(quote, quote.withPosition(position))} />
