// src/views/editor/Toggle.tsx
import React, { useContext, useState } from 'react'

enum Status {
    Viewing,
    Saving,
    Error
}
const Toggle = (props: { 
    on: boolean,
    children : React.ReactNode[] | React.ReactNode,
    save: (set: boolean) => Promise<void> | undefined
}) => {

    const [ saving, setSaving ] = useState(Status.Viewing)

    function toggle() {

        setSaving(Status.Saving)

        const promise = props.save.call(undefined, !props.on);

        if(promise === undefined) {
            setSaving(Status.Viewing);
            return;
        }

        promise
            .then(() => setSaving(Status.Viewing))
            .catch(() => setSaving(Status.Error))

    }

    return <div 
        className={
            "bookish-app-interactive" + 
                (saving === Status.Saving ? " bookish-text-editor-saving" : "") +
                (saving === Status.Error ? " bookish-text-editor-error" : "")} onClick={toggle}>
        {props.children}
    </div>

}

export default Toggle

// src/lib/components/editor/Toggle.svelte
<script lang="ts">

    enum Status {
        Viewing,
        Saving,
        Error
    }

    export let on: boolean;
    export let save: (set: boolean) => Promise<void> | undefined;

    let saving = Status.Viewing;

    function toggle() {

        saving = Status.Saving;

        const promise = save(!on);

        if(promise === undefined) {
            saving = Status.Viewing;
            return;
        }

        promise
            .then(() => saving = Status.Viewing)
            .catch(() => saving = Status.Error)

    }

</script>

<div 
    class={`bookish-app-interactive ${saving === Status.Saving ? " bookish-text-editor-saving" : ""} ${saving === Status.Error ? " bookish-text-editor-error" : ""}`}
    tabindex="0"
    role="switch"
    aria-checked={on}
    on:keydown|preventDefault={event => event.key === "Enter" || event.key === "Space" ? toggle() : undefined }
    on:click={toggle}
>
    <slot></slot>
</div>
