// src/views/editor/URLEditor.tsx
import React from "react";
import TextEditor from "./TextEditor";

const URLEditor = (props: {
    url: string,
    validator: (text: string) => undefined | string,
    edit: (newURL: string) => string | undefined
}) => {

    return <TextEditor
        placeholder="url" 
        text={props.url} 
        label="URL editor"
        valid={ url => props.validator(url) }
        save={ url => props.edit(url) }
        width={20}
        clip={true}
    />;

}

export default URLEditor;

// src/lib/components/editor/URLEditor.svelte
<script lang="ts">
    import TextEditor from './TextEditor.svelte';

    export let url: string;
    export let validator: (text: string) => undefined | string;
    export let edit: (newURL: string) => string | undefined;
</script>

<TextEditor
    placeholder="url"
    text={url}
    label="URL editor"
    valid={(url) => validator(url)}
    width={20}
    clip
    save={(url) => edit(url)}
/>
